using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bobcat.Generators;

/// <summary>
/// Generates C# source code from matched features.
/// Output targets the Bobcat runtime types (FeatureDefinition, DelegateExecutionStep, etc).
/// </summary>
public static class CodeEmitter
{
    public static string EmitFeature(FeatureInfo feature, FixtureInfo fixture, List<MatchedScenario> scenarios)
    {
        var safeClassName = SanitizeIdentifier(feature.Title) + "_Feature";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Bobcat;");
        sb.AppendLine("using Bobcat.Engine;");
        sb.AppendLine("using Bobcat.Runtime;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {fixture.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"[System.CodeDom.Compiler.GeneratedCode(\"Bobcat.Generators\", \"1.0\")]");
        sb.AppendLine($"public static class {safeClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static FeatureDefinition Define()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new FeatureDefinition(");
        sb.AppendLine($"            \"{EscapeString(feature.Title)}\",");
        sb.AppendLine($"            typeof({fixture.FullyQualifiedName}),");
        sb.AppendLine("            new ScenarioDefinition[]");
        sb.AppendLine("            {");

        foreach (var scenario in scenarios)
        {
            EmitScenario(sb, scenario, fixture);
        }

        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitScenario(StringBuilder sb, MatchedScenario scenario, FixtureInfo fixture)
    {
        var tags = scenario.Scenario.Tags;
        var tagsArray = tags.Count > 0
            ? "new[] { " + string.Join(", ", tags.Select(t => $"\"{EscapeString(t)}\"")) + " }"
            : "Array.Empty<string>()";

        sb.AppendLine($"                new ScenarioDefinition(");
        sb.AppendLine($"                    \"{EscapeString(scenario.Scenario.Title)}\",");
        sb.AppendLine($"                    {tagsArray},");
        sb.AppendLine($"                    (fixture, plan) =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var f = ({fixture.FullyQualifiedName})fixture;");

        foreach (var matched in scenario.Steps)
        {
            EmitStep(sb, matched, fixture);
        }

        sb.AppendLine("                }),");
    }

    private static void EmitStep(StringBuilder sb, MatchedStep matched, FixtureInfo fixture)
    {
        var step = matched.Step;
        var method = matched.Match.Method;
        var values = matched.Match.ExtractedValues;

        var stepKind = step.ResolvedKeyword.Trim() switch
        {
            "Given" => "StepKind.Given",
            "When" => "StepKind.When",
            "Then" => "StepKind.Then",
            _ => "StepKind.Then"
        };

        var stepId = method.MethodName;

        if (method.IsTable && step.TableRows != null && step.TableHeaders != null)
        {
            // Table grammar — emit one step per row
            for (var rowIdx = 0; rowIdx < step.TableRows.Count; rowIdx++)
            {
                var row = step.TableRows[rowIdx];
                var headers = step.TableHeaders;

                var args = BuildTableRowArgs(method, headers, row);
                var rowStepId = $"{stepId}.row{rowIdx + 1}";

                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{EscapeString(rowStepId)}\",");
                sb.AppendLine($"                        {stepKind},");
                sb.AppendLine($"                        \"{EscapeString(step.Text)} (row {rowIdx + 1})\",");
                sb.AppendLine($"                        (ctx, result, ct) => {{ f.{method.MethodName}({args}); return Task.CompletedTask; }}));");
            }
        }
        else if (method.IsSetVerification && step.TableRows != null && step.TableHeaders != null)
        {
            // Set verification — emit comparison code
            EmitSetVerificationStep(sb, step, method, stepId, stepKind);
        }
        else
        {
            // Regular sentence step
            var args = BuildSentenceArgs(method, values);
            var awaitPrefix = method.IsAsync ? "await " : "";
            var returnSuffix = method.IsAsync ? "" : " return Task.CompletedTask;";

            if (method.StepKind == "Check")
            {
                // Check (bool return) — assertion failure, not critical
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{EscapeString(stepId)}\",");
                sb.AppendLine($"                        StepKind.Then,");
                sb.AppendLine($"                        \"{EscapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ if (!await f.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); }}));");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ if (!f.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); return Task.CompletedTask; }}));");
                }
            }
            else
            {
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{EscapeString(stepId)}\",");
                sb.AppendLine($"                        {stepKind},");
                sb.AppendLine($"                        \"{EscapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {awaitPrefix}f.{method.MethodName}({args}); }}));");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ f.{method.MethodName}({args});{returnSuffix} }}));");
                }
            }
        }
    }

    private static void EmitSetVerificationStep(StringBuilder sb, StepInfo step, StepMethodInfo method, string stepId, string stepKind)
    {
        var keyColumns = string.IsNullOrEmpty(method.SetVerificationKeyColumns)
            ? "Array.Empty<string>()"
            : "new[] { " + string.Join(", ", method.SetVerificationKeyColumns.Split(',').Select(k => $"\"{EscapeString(k.Trim())}\"")) + " }";

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{EscapeString(stepId)}\",");
        sb.AppendLine($"                        StepKind.Then,");
        sb.AppendLine($"                        \"{EscapeString(step.Text)}\",");

        if (method.IsAsync)
        {
            sb.AppendLine($"                        async (ctx, result, ct) =>");
        }
        else
        {
            sb.AppendLine($"                        (ctx, result, ct) =>");
        }

        sb.AppendLine("                    {");

        var awaitPrefix = method.IsAsync ? "await " : "";
        sb.AppendLine($"                        var actual = {awaitPrefix}f.{method.MethodName}();");
        sb.AppendLine($"                        var expected = new List<Dictionary<string, string>>");
        sb.AppendLine("                        {");

        if (step.TableRows != null && step.TableHeaders != null)
        {
            foreach (var row in step.TableRows)
            {
                sb.AppendLine("                            new Dictionary<string, string>");
                sb.AppendLine("                            {");
                for (var i = 0; i < step.TableHeaders.Count && i < row.Count; i++)
                {
                    sb.AppendLine($"                                [\"{EscapeString(step.TableHeaders[i])}\"] = \"{EscapeString(row[i])}\",");
                }
                sb.AppendLine("                            },");
            }
        }

        sb.AppendLine("                        };");
        sb.AppendLine($"                        SetVerificationComparer.Compare(actual, expected, {keyColumns}, result);");

        if (!method.IsAsync)
        {
            sb.AppendLine("                        return Task.CompletedTask;");
        }

        sb.AppendLine("                    }));");
    }

    private static string BuildSentenceArgs(StepMethodInfo method, List<string> values)
    {
        if (method.Parameters.Count == 0 || values.Count == 0) return "";

        var args = new List<string>();
        for (var i = 0; i < method.Parameters.Count && i < values.Count; i++)
        {
            var param = method.Parameters[i];
            var value = values[i];
            args.Add(CucumberExpressionParser.ToCSharpLiteral(value, param.Type));
        }

        return string.Join(", ", args);
    }

    private static string BuildTableRowArgs(StepMethodInfo method, List<string> headers, List<string> row)
    {
        var args = new List<string>();
        foreach (var param in method.Parameters)
        {
            var colIndex = headers.FindIndex(h =>
                string.Equals(h, param.Name, StringComparison.OrdinalIgnoreCase));

            if (colIndex >= 0 && colIndex < row.Count)
            {
                args.Add(CucumberExpressionParser.ToCSharpLiteral(row[colIndex], param.Type));
            }
            else
            {
                args.Add($"default({param.Type})");
            }
        }

        return string.Join(", ", args);
    }

    public static string SanitizeIdentifier(string text)
    {
        var sb = new StringBuilder();
        foreach (var c in text)
        {
            if (char.IsLetterOrDigit(c))
                sb.Append(c);
            else if (c == ' ')
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

public class MatchedScenario
{
    public ScenarioInfo Scenario { get; set; } = null!;
    public List<MatchedStep> Steps { get; set; } = new();
}

public class MatchedStep
{
    public StepInfo Step { get; set; } = null!;
    public StepMatcher.MatchResult Match { get; set; } = null!;
}
