using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bobcat.Generators;

/// <summary>
/// Generates C# source code from matched features.
/// Output targets the Bobcat runtime types (FeatureDefinition, DelegateExecutionStep, etc).
/// </summary>
public static class CodeEmitter
{
    public static string EmitFeature(FeatureInfo feature, FixtureInfo fixture, List<MatchedScenario> scenarios)
        => EmitFeature(feature, fixture, scenarios, out _);

    /// <summary>
    /// Emit the feature, and report any written value that could not be read as the parameter it
    /// binds to. A non-empty <paramref name="unreadable"/> means the emitted source would not
    /// compile — the caller reports BOBCAT030 and adds nothing.
    /// </summary>
    public static string EmitFeature(FeatureInfo feature, FixtureInfo fixture,
        List<MatchedScenario> scenarios, out List<CellLiterals.UnreadableValue> unreadable)
    {
        unreadable = CellLiterals.StartCollecting();
        try
        {
            return emitFeature(feature, fixture, scenarios);
        }
        finally
        {
            CellLiterals.StopCollecting();
        }
    }

    private static string emitFeature(FeatureInfo feature, FixtureInfo fixture, List<MatchedScenario> scenarios)
    {
        var safeClassName = SanitizeIdentifier(feature.Title) + "_Feature";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Bobcat;");
        sb.AppendLine("using Bobcat.Engine;");
        sb.AppendLine("using Bobcat.Engine.Verification;");
        sb.AppendLine("using Bobcat.Runtime;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        // Empty means the fixture is in the global namespace — emit no declaration at all rather
        // than a bare `namespace ;`. FullyQualifiedName is `global::`-prefixed either way, so the
        // generated code binds to the fixture from wherever it lands. See issue #269.
        if (fixture.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {fixture.Namespace};");
            sb.AppendLine();
        }
        sb.AppendLine($"[System.CodeDom.Compiler.GeneratedCode(\"Bobcat.Generators\", \"1.0\")]");
        sb.AppendLine($"public static class {safeClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static FeatureDefinition Define()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new FeatureDefinition(");
        sb.AppendLine($"            \"{escapeString(feature.Title)}\",");
        sb.AppendLine($"            typeof({fixture.FullyQualifiedName}),");
        sb.AppendLine("            new ScenarioDefinition[]");
        sb.AppendLine("            {");

        foreach (var scenario in scenarios)
        {
            emitScenario(sb, scenario, fixture);
        }

        sb.AppendLine("            })");
        sb.AppendLine("        {");
        if (feature.Tags.Count > 0)
            sb.AppendLine($"            Tags = new[] {{ {string.Join(", ", feature.Tags.Select(t => $"\"{escapeString(t)}\""))} }},");
        if (feature.Description != null)
            sb.AppendLine($"            Description = \"{escapeString(feature.Description)}\",");
        emitHook(sb, fixture, HookKind.BeforeEach);
        emitHook(sb, fixture, HookKind.AfterEach);
        emitHook(sb, fixture, HookKind.BeforeAll);
        emitHook(sb, fixture, HookKind.AfterAll);
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emit the discovered lifecycle hooks of one kind as a single delegate. Parameters are
    /// resolved by type at compile time, exactly like step arguments — no reflection.
    /// </summary>
    private static void emitHook(StringBuilder sb, FixtureInfo fixture, HookKind kind)
    {
        var hooks = fixture.HooksOf(kind).ToList();
        if (hooks.Count == 0) return;

        var featureLevel = kind == HookKind.BeforeAll || kind == HookKind.AfterAll;
        var signature = featureLevel ? "async (ctx) =>" : "async (fixture, ctx) =>";

        sb.AppendLine($"            {kind} = {signature}");
        sb.AppendLine("            {");

        if (!featureLevel)
            sb.AppendLine($"                var f = ({fixture.FullyQualifiedName})fixture;");

        // Keeps the lambda legally async even when every hook is synchronous.
        sb.AppendLine("                await Task.CompletedTask;");

        foreach (var hook in hooks)
        {
            var target = featureLevel ? fixture.FullyQualifiedName : "f";
            var args = string.Join(", ", hook.Parameters.Select(p => injectionExpression(p, null)));
            var awaitKw = hook.IsAsync ? "await " : "";
            sb.AppendLine($"                {awaitKw}{target}.{hook.MethodName}({args});");
        }

        sb.AppendLine("            },");
    }

    private static void emitScenario(StringBuilder sb, MatchedScenario scenario, FixtureInfo fixture)
    {
        var tags = scenario.Scenario.Tags;
        var tagsArray = tags.Count > 0
            ? "new[] { " + string.Join(", ", tags.Select(t => $"\"{escapeString(t)}\"")) + " }"
            : "Array.Empty<string>()";

        sb.AppendLine($"                new ScenarioDefinition(");
        sb.AppendLine($"                    \"{escapeString(scenario.Scenario.Title)}\",");
        sb.AppendLine($"                    {tagsArray},");
        sb.AppendLine($"                    (fixture, plan) =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var f = ({fixture.FullyQualifiedName})fixture;");

        // Declare instances for the grammar modules used by this scenario (one per scenario).
        // A module whose construction resolves nothing from the scenario is built eagerly at
        // plan-build time, with the [IncludeGrammars] literals (issue #212 phase 2). One that
        // injects from the scenario scope (IStepContext, a resource, a service) is declared
        // null here and constructed lazily by the first step that uses it — the scope only
        // exists inside the step lambdas.
        var usedModules = scenario.Steps
            .Where(s => s.Match != null)
            .Select(s => s.Match!.Method.DeclaringModule)
            .Where(m => m != null)
            .Distinct()
            .ToList();
        foreach (var moduleFqn in usedModules)
        {
            var module = fixture.FindModule(moduleFqn!);
            var local = fixture.ModuleLocal(moduleFqn!);

            if (module is { RequiresContext: true })
                sb.AppendLine($"                    {module.FullyQualifiedName}? {local} = null;");
            else
                sb.AppendLine($"                    var {local} = {moduleConstruction(module, moduleFqn!)};");
        }

        foreach (var matched in scenario.Steps)
        {
            emitStep(sb, matched, fixture);
        }

        sb.AppendLine("                }),");
    }

    private static void emitStep(StringBuilder sb, MatchedStep matched, FixtureInfo fixture)
    {
        // So an unreadable value can name the step it was written in.
        CellLiterals.CurrentStep(matched.Step.Text);

        var step = matched.Step;

        var stepKind = step.ResolvedKeyword.Trim() switch
        {
            "Given" => "StepKind.Given",
            "When" => "StepKind.When",
            "Then" => "StepKind.Then",
            _ => "StepKind.Then"
        };

        if (matched.GrammarMatch != null)
        {
            emitTableGrammarStep(sb, step, matched.GrammarMatch, stepKind);
            return;
        }

        var method = matched.Match!.Method;
        var values = matched.Match.ExtractedValues;

        var stepId = method.MethodName;

        // Call routing: the fixture itself ("f") or a per-scenario grammar-module instance.
        var target = method.DeclaringModule == null ? "f" : fixture.ModuleLocal(method.DeclaringModule);
        var module = method.DeclaringModule == null ? null : fixture.FindModule(method.DeclaringModule);
        var ctxStmt = "";
        if (module != null)
        {
            if (module.RequiresContext)
            {
                // Lazy per-scenario construction (issue #212 phase 2): the first step using the
                // module constructs it inside the scenario scope, where ctx exists; later steps
                // see the same instance through the ??=. Steps run sequentially, so no race.
                var holder = target;
                target = holder + "i";
                ctxStmt = $"var {target} = {holder} ??= {moduleConstruction(module, method.DeclaringModule!)}; ";
            }

            // A module that inherits Fixture receives the step context before its method runs.
            if (module.IsFixture) ctxStmt += $"{target}.Context = ctx; ";
        }

        // Does this comparison have a return-value capture? (one capture beyond the value params)
        // A fact's return value is its VERDICT, never something to compare — and a tuple return is
        // compared element by element instead. `[Step]` (keywordless) compares like `[Then]`: the
        // keyword decides which Gherkin keywords a step matches under, not whether it asserts.
        var compareReturn = method.HasReturnValue && !method.IsFact && !method.ComparesTuple
            && method.StepKind is "Then" or ""
            && values.Count == valueParamCount(method) + 1;
        var compareTuple = method.ComparesTuple
            && values.Count == valueParamCount(method) + method.ReturnTupleElements.Count;
        var isComparison = !method.IsTable && !method.IsSetVerification && !method.IsDecisionTable
            && (method.OutParameters.Count > 0 || compareReturn || compareTuple);

        // [NewScope] — this step's injected services come from a child scope nested under
        // the scenario scope, disposed when the step finishes.
        var scopeStmt = method.NewScope ? childScopeStatement(method, "__sc") + " " : "";
        var scopeProvider = method.NewScope ? "__sc.ServiceProvider" : null;

        // The step's compile-time binding (issue #208): the match the emit below acts on,
        // written down for the preview command.
        var declaringType = method.DeclaringModule ?? fixture.FullyQualifiedName;

        if (method.IsDecisionTable && step.TableRows != null && step.TableHeaders != null)
        {
            emitRowTableStep(sb, step, method, stepId, target, ctxStmt, declaringType, values, scopeStmt,
                scopeProvider, stepKind);
        }
        else if (method.IsTable && step.TableRows != null && step.TableHeaders != null)
        {
            // The same grid, with nothing compared: a [Table] step's columns are all inputs and its
            // return value, if it has one, is not an expectation — that is what [DecisionTable]
            // means. [NewScope] on a [Table] step has always meant a scope per row, because every
            // row used to be its own step.
            emitRowTableStep(sb, step, method, stepId, target, ctxStmt, declaringType, values,
                stepKind: stepKind, compareOutputs: false,
                scopePerRow: method.ScopePerRow || method.NewScope);
        }
        else if (method.IsSetVerification && step.TableRows != null && step.TableHeaders != null)
        {
            // Set verification — emit comparison code
            var binding = bindingInitializer(declaringType, method.MethodName, method.Expression,
                bindingArgsFromCaptures(method.Parameters, values, step.DocString));
            emitSetVerificationStep(sb, step, method, stepId, stepKind, target, ctxStmt, values, binding);
        }
        else if (method.WaitForTimeoutMs.HasValue)
        {
            var waitArgs = bindingArgsFromCaptures(method.Parameters, values, step.DocString);
            if (compareReturn) withReturnCompare(waitArgs, method, values);
            if (compareTuple) withTupleCompare(waitArgs, method, values);
            var binding = bindingInitializer(declaringType, method.MethodName, method.Expression, waitArgs);
            emitWaitForStep(sb, step, method, stepId, stepKind, values, compareReturn, isComparison, target, ctxStmt,
                binding, scopeStmt, scopeProvider);
        }
        else if (isComparison)
        {
            var comparisonArgs = bindingArgsFromCaptures(method.Parameters, values, step.DocString);
            if (compareReturn) withReturnCompare(comparisonArgs, method, values);
            if (compareTuple) withTupleCompare(comparisonArgs, method, values);
            var binding = bindingInitializer(declaringType, method.MethodName, method.Expression, comparisonArgs);
            emitComparisonStep(sb, step, method, stepId, stepKind, values, compareReturn, target, ctxStmt,
                binding, scopeStmt, scopeProvider, compareTuple);
        }
        else
        {
            // Regular sentence step
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            var awaitPrefix = method.IsAsync ? "await " : "";
            var returnSuffix = method.IsAsync ? "" : " return Task.CompletedTask;";
            var binding = bindingInitializer(declaringType, method.MethodName, method.Expression,
                bindingArgsFromCaptures(method.Parameters, values, step.DocString));

            if (method.IsFact)
            {
                // A Fact: the bool return IS the verdict — an assertion failure, not a critical one,
                // so the scenario carries on to its next step. True for [Check] and for any step
                // method returning bool (or Task<bool>) with no expected cell in its sentence.
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{escapeString(stepId)}\",");
                sb.AppendLine($"                        StepKind.Then,");
                sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}if (!await {target}.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); }}) {binding});");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}if (!{target}.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); return Task.CompletedTask; }}) {binding});");
                }
            }
            else
            {
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{escapeString(stepId)}\",");
                sb.AppendLine($"                        {stepKind},");
                sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}{awaitPrefix}{target}.{method.MethodName}({args}); }}) {binding});");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}{target}.{method.MethodName}({args});{returnSuffix} }}) {binding});");
                }
            }
        }
    }

    /// <summary>
    /// Emit a <c>[TableGrammar]</c> envelope: a fresh grammar instance, <c>Before</c> once,
    /// then one <c>Row</c> call per table row, then <c>After</c> in a <c>finally</c> so it runs
    /// even when <c>Before</c> or a row threw.
    /// </summary>
    private static void emitTableGrammarStep(StringBuilder sb, StepInfo step,
        StepMatcher.TableGrammarMatch match, string stepKind)
    {
        var grammar = match.Grammar;
        var row = grammar.Row;
        var headers = step.TableHeaders!;
        var rows = step.TableRows!;
        var values = match.ExtractedValues;

        // Columns the Row method consumes as inputs. An explicitly-injected parameter never
        // claims a column, so [FromScopedService] on a parameter named like a header still
        // leaves that header available as an expected value.
        var boundHeaders = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in row?.Parameters ?? new List<ParameterInfo>())
        {
            if (p.IsExplicitlyInjected) continue;
            var header = headers.FirstOrDefault(h => string.Equals(h, p.ColumnName, StringComparison.OrdinalIgnoreCase));
            if (header != null) boundHeaders.Add(header);
        }

        var leftover = headers.Where(h => !boundHeaders.Contains(h)).ToList();

        // Decision-table disambiguation: a Row return plus exactly one unbound column means
        // that column is the expected output. WITH a recipe, Row's return is a product to
        // persist instead, so nothing is treated as an expected value.
        var expectedColumn = grammar.HasRecipe
            ? null
            : grammar.RowExpectedColumn != null
                ? headers.FirstOrDefault(h => string.Equals(h, grammar.RowExpectedColumn, StringComparison.OrdinalIgnoreCase))
                : (row is { HasReturnValue: true } && leftover.Count == 1 ? leftover[0] : null);

        var opts = grammar.ApproxTolerance.HasValue
            ? $"new CheckOptions {{ Tolerance = {grammar.ApproxTolerance.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)} }}"
            : "null";

        var columnsLiteral = string.Join(", ", headers.Select(h => $"\"{escapeString(h)}\""));

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(grammar.ClassName)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        async (ctx, result, ct) =>");
        sb.AppendLine("                    {");
        // Keeps the lambda legally async when every envelope method is synchronous.
        sb.AppendLine("                        await Task.CompletedTask;");
        // Fresh instance per execution, so Before's session and After's save share fields.
        sb.AppendLine($"                        var g__ = new {grammar.FullyQualifiedName}();");
        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        // As with a decision table: whatever rows were reached still render, even when Before, a
        // row, or After throws.
        sb.AppendLine("                        try");
        sb.AppendLine("                        {");

        if (grammar.HasRecipe)
        {
            // The one runtime-resolved piece: the recipe's behavior lives in the extension
            // package (Marten/EF), which the netstandard2.0 generator must not reference.
            sb.AppendLine($"                        await using var behavior__ = Bobcat.Runtime.GrammarBehaviors.Resolve(typeof({grammar.FullyQualifiedName}));");
        }

        sb.AppendLine("                        try");
        sb.AppendLine("                        {");

        if (grammar.HasRecipe)
            sb.AppendLine("                            await behavior__.Open(ctx);");

        if (grammar.Before != null)
        {
            var beforeArgs = buildArgsFromCaptures(grammar.Before.Parameters, values, null, null);
            var awaitBefore = grammar.Before.IsAsync ? "await " : "";
            sb.AppendLine($"                            {awaitBefore}g__.{grammar.Before.MethodName}({beforeArgs});");
        }

        var awaitRow = row is { IsAsync: true } ? "await " : "";

        for (var r = 0; r < rows.Count; r++)
        {
            var rowCells = rows[r];
            sb.AppendLine($"                            // row {r + 1}");
            sb.AppendLine("                            {");
            // Row-level progress: to the executor the whole table is one step, so without this
            // a 200-row grammar is the least observable thing in a suite. Message-less on
            // purpose — see StepUpdate.ForRow.
            sb.AppendLine($"                                ctx.ReportProgress(global::Bobcat.Engine.StepUpdate.ForRow({r + 1}, {rows.Count}));");

            var rowScopeProvider = grammar.ScopePerRow ? $"__sc{r}.ServiceProvider" : null;
            if (grammar.ScopePerRow)
            {
                var resource = grammar.ScopeResourceName == null
                    ? "null"
                    : $"\"{escapeString(grammar.ScopeResourceName)}\"";
                sb.AppendLine($"                                using var __sc{r} = Bobcat.Runtime.HostResourceExtensions.CreateChildScope(ctx, {resource});");
            }

            if (grammar.HasRecipe)
            {
                // With a recipe, each row produces a product that the behavior persists.
                // A hand-written Row is the override for custom construction; without one,
                // columns bind straight to the entity's constructor or settable properties.
                var product = row != null
                    ? $"{awaitRow}g__.{row.MethodName}({buildArgsFromColumns(row.Parameters, values, headers, rowCells, rowScopeProvider)})"
                    : buildEntityFromColumns(grammar, headers, rowCells);

                sb.AppendLine($"                                var product{r}__ = {product};");
                sb.AppendLine($"                                await behavior__.Row(product{r}__);");
            }
            else if (expectedColumn != null)
            {
                var rowArgs = buildArgsFromColumns(row!.Parameters, values, headers, rowCells, rowScopeProvider);
                sb.AppendLine($"                                var row{r}__ = {awaitRow}g__.{row.MethodName}({rowArgs});");
            }
            else
            {
                var rowArgs = buildArgsFromColumns(row!.Parameters, values, headers, rowCells, rowScopeProvider);
                sb.AppendLine($"                                {awaitRow}g__.{row.MethodName}({rowArgs});");
            }

            foreach (var header in headers)
            {
                var idx = headers.FindIndex(h => string.Equals(h, header, StringComparison.OrdinalIgnoreCase));
                var value = idx >= 0 && idx < rowCells.Count ? rowCells[idx] : "";

                if (expectedColumn != null && string.Equals(header, expectedColumn, StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"                                cells__.Add(CellCheck.For<{row!.QualifiedReturnType}>(\"{escapeString(header)}\", row{r}__, \"{escapeString(value)}\", {opts}, {r}));");
                }
                else
                {
                    // Input (or otherwise unconsumed) column — rendered plain. The plain-value
                    // constructor on purpose: nothing was judged here, which is what the report
                    // reads to decide the column earns no Status. Its text travels as
                    // StepCell.Value (issue #396).
                    sb.AppendLine($"                                cells__.Add(new CellResult(\"{escapeString(header)}\", ResultStatus.ok, \"{escapeString(value)}\") {{ RowIndex = {r} }});");
                }
            }

            sb.AppendLine("                            }");
        }

        sb.AppendLine("                        }");
        sb.AppendLine("                        finally");
        sb.AppendLine("                        {");

        if (grammar.After != null)
        {
            var afterArgs = buildArgsFromCaptures(grammar.After.Parameters, values, null, null);
            var awaitAfter = grammar.After.IsAsync ? "await " : "";
            sb.AppendLine($"                            {awaitAfter}g__.{grammar.After.MethodName}({afterArgs});");
        }
        else if (!grammar.HasRecipe)
        {
            sb.AppendLine("                            // no After method on this grammar");
        }

        // The recipe closes last, so a hand-written After can still touch the session before
        // the single SaveChangesAsync.
        if (grammar.HasRecipe)
            sb.AppendLine("                            await behavior__.Close();");

        sb.AppendLine("                        }");
        sb.AppendLine("                        }");
        sb.AppendLine("                        finally");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            DecisionTableComparer.Apply(result, new[] {{ {columnsLiteral} }}, cells__);");
        sb.AppendLine("                        }");

        // The grammar's binding: the class is the match, Row (or the recipe entity's
        // construction) is what each data row feeds, and the expected column — when the table
        // is a decision table — is the compared output.
        var bindingArgs = row != null
            ? bindingArgsFromColumns(row.Parameters, values, headers)
            : headers.Where(h => expectedColumn == null || !string.Equals(h, expectedColumn, StringComparison.OrdinalIgnoreCase))
                .Select(h => bindingArgLiteral(h, h, "TableColumn")).ToList();
        if (expectedColumn != null)
            bindingArgs.Add(bindingArgLiteral(expectedColumn, expectedColumn, "Expected"));

        var boundMethod = row?.MethodName
            ?? (grammar.RecipeEntity != null ? $"new {grammar.RecipeEntity.Name}" : "Row");
        var binding = bindingInitializer(grammar.FullyQualifiedName, boundMethod, grammar.Expression, bindingArgs);
        sb.AppendLine($"                    }}) {binding});");
    }

    /// <summary>
    /// Convention entity construction: bind columns to the entity's constructor parameters
    /// first (records-friendly), then to settable properties, by header name with the same
    /// type conversion the rest of the generator uses. Emitted as a direct <c>new Customer(...)</c>
    /// — no runtime binder. A hand-written <c>Row</c> is the override for anything this can't do.
    /// </summary>
    private static string buildEntityFromColumns(TableGrammarInfo grammar, List<string> headers, List<string> row)
    {
        var entity = grammar.RecipeEntity!;

        string? Cell(string name)
        {
            var idx = headers.FindIndex(h => string.Equals(h, name, StringComparison.OrdinalIgnoreCase));
            return idx >= 0 && idx < row.Count ? row[idx] : null;
        }

        // Prefer the public constructor that covers the most headers and whose every parameter
        // a column can actually supply.
        List<ParameterInfo>? best = null;
        foreach (var ctor in entity.Constructors)
        {
            var usable = ctor.All(p => p.IsSimpleType && Cell(p.Name) != null);
            if (!usable) continue;
            if (best == null || ctor.Count > best.Count) best = ctor;
        }

        if (best != null)
        {
            var args = best.Select(p =>
                $"{p.Name}: {CucumberExpressionParser.ToCSharpLiteral(Cell(p.Name)!, p)}");
            return $"new {entity.FullyQualifiedName}({string.Join(", ", args)})";
        }

        if (entity.HasParameterlessConstructor)
        {
            var assignments = entity.SettableProperties
                .Where(p => p.IsSimpleType && Cell(p.Name) != null)
                .Select(p => $"{p.Name} = {CucumberExpressionParser.ToCSharpLiteral(Cell(p.Name)!, p)}")
                .ToList();

            if (assignments.Count > 0)
                return $"new {entity.FullyQualifiedName} {{ {string.Join(", ", assignments)} }}";
        }

        throw new InvalidOperationException(
            $"Cannot construct '{entity.Name}' from the columns [{string.Join(", ", headers)}] on grammar " +
            $"'{grammar.ClassName}'. No public constructor's parameters are all supplied by columns, and " +
            "no settable properties match. Write a Row method returning the entity to control construction.");
    }

    private static void emitSetVerificationStep(StringBuilder sb, StepInfo step, StepMethodInfo method, string stepId, string stepKind, string target, string ctxStmt, List<string> values, string binding)
    {
        // The key list is read by the runtime's own parser rather than split here, so "Sku, Name"
        // cannot mean one thing in an attribute and another as a VerifySet argument. Same move as
        // emitting CellValues.Read for a cell instead of deciding its value at compile time: the
        // generated code runs in an assembly that references Bobcat, so there is no reason for a
        // second reading to exist. (The agreement-test pattern elsewhere exists for the opposite
        // case — a split the netstandard2.0 generator has to perform itself.)
        var keyColumns = string.IsNullOrEmpty(method.SetVerificationKeyColumns)
            ? "global::System.Array.Empty<string>()"
            : $"global::Bobcat.Runtime.SetVerificationComparer.ParseKeyColumns(\"{escapeString(method.SetVerificationKeyColumns)}\")";

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        StepKind.Then,");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");

        if (method.IsAsync)
        {
            sb.AppendLine($"                        async (ctx, result, ct) =>");
        }
        else
        {
            sb.AppendLine($"                        (ctx, result, ct) =>");
        }

        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");

        // Captures bind positionally as on any sentence step, so "{event} is emitted with:" can
        // hand the method the type it is asked about; a StepTable parameter sees the expected rows.
        var svArgs = buildArgsFromCaptures(method.Parameters, values, step.DocString, null, tableLiteral(step));
        var awaitPrefix = method.IsAsync ? "await " : "";
        sb.AppendLine($"                        var actual = {awaitPrefix}{target}.{method.MethodName}({svArgs});");
        sb.AppendLine($"                        var expected = new List<Dictionary<string, string>>");
        sb.AppendLine("                        {");

        if (step.TableRows != null && step.TableHeaders != null)
        {
            foreach (var row in step.TableRows)
            {
                sb.AppendLine("                            new Dictionary<string, string>");
                sb.AppendLine("                            {");
                for (var i = 0; i < step.TableHeaders.Count && i < row.Count; i++)
                {
                    sb.AppendLine($"                                [\"{escapeString(step.TableHeaders[i])}\"] = \"{escapeString(row[i])}\",");
                }
                sb.AppendLine("                            },");
            }
        }

        sb.AppendLine("                        };");
        var ordered = method.SetVerificationOrdered ? ", ordered: true" : "";
        var scalarColumn = string.IsNullOrEmpty(method.SetVerificationColumn)
            ? ""
            : $", scalarColumn: \"{escapeString(method.SetVerificationColumn)}\"";

        // The header row, passed separately from the rows. Read off the first expected row instead,
        // a table with a header and nothing under it has no columns at all — and "the set should be
        // empty" is a real expectation whose extra rows then render under no headings.
        var columns = step.TableHeaders != null
            ? ", columns: new[] { "
              + string.Join(", ", step.TableHeaders.Select(h => $"\"{escapeString(h)}\""))
              + " }"
            : "";

        sb.AppendLine($"                        SetVerificationComparer.Compare(actual, expected, {keyColumns}, result{ordered}{scalarColumn}{columns});");

        if (!method.IsAsync)
        {
            sb.AppendLine("                        return Task.CompletedTask;");
        }

        sb.AppendLine($"                    }}) {binding});");
    }

    /// <summary>
    /// Emit a sentence step that verifies actual-vs-expected via the return value and/or
    /// out parameters. Captures map positionally to parameters; the return-value expected
    /// (when present) is the trailing capture.
    /// </summary>
    private static void emitComparisonStep(StringBuilder sb, StepInfo step, StepMethodInfo method,
        string stepId, string stepKind, List<string> values, bool compareReturn, string target, string ctxStmt,
        string binding, string scopeStmt = "", string? scopeProvider = null, bool compareTuple = false)
    {
        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        {(method.IsAsync ? "async " : "")}(ctx, result, ct) =>");
        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                        {scopeStmt.TrimEnd()}");

        var callArgs = new List<string>();
        var outCompares = new List<(string Name, string Local, string Type, string Expected)>();
        var vi = 0;
        foreach (var p in method.Parameters)
        {
            if (p.IsInjected)
            {
                callArgs.Add(injectionExpression(p, scopeProvider));
                continue;
            }

            var capture = vi < values.Count ? values[vi] : "";
            vi++;

            if (p.IsOut)
            {
                var local = "out__" + p.Name;
                sb.AppendLine($"                        {p.QualifiedType} {local};");
                callArgs.Add($"out {local}");
                outCompares.Add((p.Name, local, p.QualifiedType, capture));
            }
            else
            {
                callArgs.Add(CucumberExpressionParser.ToCSharpLiteral(capture, p));
            }
        }

        var opts = emitCheckOptions(method);
        var awaitKw = method.IsAsync ? "await " : "";
        var argList = string.Join(", ", callArgs);

        if (compareReturn || compareTuple)
            sb.AppendLine($"                        var actual__ret = {awaitKw}{target}.{method.MethodName}({argList});");
        else
            sb.AppendLine($"                        {awaitKw}{target}.{method.MethodName}({argList});");

        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        foreach (var (name, local, type, expected) in outCompares)
        {
            sb.AppendLine($"                        cells__.Add(CellCheck.For<{type}>(\"{escapeString(name)}\", {local}, \"{escapeString(expected)}\", {opts}));");
        }

        if (compareReturn)
        {
            var col = method.ReturnColumn ?? "result";
            var retExpected = values[valueParamCount(method)];
            sb.AppendLine($"                        cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(col)}\", actual__ret, \"{escapeString(retExpected)}\", {opts}));");
        }

        if (compareTuple)
        {
            // One cell per tuple element, each judged on its own — the same shape `out` parameters
            // produce above, and the only shape an async method can produce at all.
            var first = valueParamCount(method);
            for (var i = 0; i < method.ReturnTupleElements.Count; i++)
            {
                var element = method.ReturnTupleElements[i];
                var expected = first + i < values.Count ? values[first + i] : "";
                sb.AppendLine(
                    $"                        cells__.Add(CellCheck.For<{element.QualifiedType}>(" +
                    $"\"{escapeString(element.Name)}\", actual__ret.{element.Name}, " +
                    $"\"{escapeString(expected)}\", {opts}));");
            }
        }

        sb.AppendLine("                        result.MarkCells(cells__.ToArray());");
        sb.AppendLine("                        if (cells__.Exists(c => c.Status != ResultStatus.success)) result.MarkFailed(); else result.MarkSuccess();");

        if (!method.IsAsync)
            sb.AppendLine("                        return Task.CompletedTask;");

        sb.AppendLine($"                    }}) {binding});");
    }

    /// <summary>
    /// Emit a table of rows as one step rendering one grid: the method is called once per row,
    /// input columns supply its arguments, and <c>out</c>/return columns are compared as expected
    /// outputs.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Serves both <c>[DecisionTable]</c> and the plain per-row <c>[Table]</c> step, which differ
    /// only in whether anything is compared — <paramref name="compareOutputs"/>. A <c>[Table]</c>
    /// step used to emit one <c>DelegateExecutionStep</c> per row, reading
    /// <c>Given the users are (row 2)</c> once per row with the values it arranged appearing
    /// nowhere; the specification could not be read back from its own report, which is the whole
    /// point of a grid.
    /// </para>
    /// <para>
    /// <b>A row that throws is a failed row, not a failed step.</b> Each call is wrapped so the
    /// exception becomes a <c>row-error</c> cell on that row and the remaining rows still run —
    /// Storyteller's behaviour, and the right one for a table, where a row is an independent case
    /// rather than a step in a sequence. The escape hatch is Bobcat's own failure vocabulary: a
    /// <c>SpecCriticalException</c> still aborts the scenario and a <c>SpecCatastrophicException</c>
    /// still stops the suite, so a fixture that means "stop" can still say so, and cancellation
    /// propagates untouched. See <c>DecisionTableComparer.IsRowFailure</c>.
    /// </para>
    /// </remarks>
    private static void emitRowTableStep(StringBuilder sb, StepInfo step, StepMethodInfo method, string stepId,
        string target, string ctxStmt, string declaringType, List<string> values, string scopeStmt = "",
        string? stepScopeProvider = null, string stepKind = "StepKind.Then", bool compareOutputs = true,
        bool? scopePerRow = null)
    {
        var headers = step.TableHeaders!;
        var rows = step.TableRows!;

        // Classify each header: input param, out param, the return value, or unknown (echo).
        var returnColumn = compareOutputs
            ? method.ReturnColumn ?? (method.HasReturnValue ? method.MethodName : null)
            : null;
        var outParameters = compareOutputs ? method.OutParameters : new List<ParameterInfo>();

        ParameterInfo? FindParam(string header) =>
            method.Parameters.FirstOrDefault(p =>
                string.Equals(p.ColumnName, header, StringComparison.OrdinalIgnoreCase));

        bool IsCompared(string header)
        {
            var param = FindParam(header);
            if (compareOutputs && param != null && param.IsOut) return true;
            return returnColumn != null
                   && string.Equals(header, returnColumn, StringComparison.OrdinalIgnoreCase);
        }

        var opts = emitCheckOptions(method);
        var perRowScope = scopePerRow ?? method.ScopePerRow;

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        {(method.IsAsync ? "async " : "")}(ctx, result, ct) =>");
        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                        {scopeStmt.TrimEnd()}");
        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        var columnsLiteral = string.Join(", ", headers.Select(h => $"\"{escapeString(h)}\""));
        var awaitKw = method.IsAsync ? "await " : "";

        // The grid is the report, so the rows that were reached are rendered even when the step is
        // cut short by a critical failure: `Apply` runs in a finally.
        sb.AppendLine("                        try");
        sb.AppendLine("                        {");

        for (var r = 0; r < rows.Count; r++)
        {
            var row = rows[r];
            string Cell(string header)
            {
                var idx = headers.FindIndex(h => string.Equals(h, header, StringComparison.OrdinalIgnoreCase));
                return idx >= 0 && idx < row.Count ? row[idx] : "";
            }

            sb.AppendLine($"                            // row {r + 1}");
            sb.AppendLine("                            {");

            // Row-level progress: to the executor the whole table is one step, so without this a
            // 200-row table is the least observable thing in a suite. Message-less on purpose —
            // see StepUpdate.ForRow.
            sb.AppendLine($"                                ctx.ReportProgress(global::Bobcat.Engine.StepUpdate.ForRow({r + 1}, {rows.Count}));");

            // Declared before the try and initialised, because the call may never assign them.
            foreach (var outParam in outParameters)
            {
                sb.AppendLine($"                                {outParam.QualifiedType} dt{r}__{outParam.Name} = default!;");
            }
            if (returnColumn != null)
                sb.AppendLine($"                                {method.QualifiedReturnType} dt{r}__ret = default!;");

            sb.AppendLine("                                try");
            sb.AppendLine("                                {");

            // [ScopePerRow] — each row's injected services come from their own child scope.
            var rowScopeLocal = $"__sc{r}";
            var rowScopeProvider = perRowScope ? $"{rowScopeLocal}.ServiceProvider" : stepScopeProvider;
            if (perRowScope)
            {
                sb.AppendLine($"                                    using (var {rowScopeLocal} = {childScopeExpression(method)})");
                sb.AppendLine("                                    {");
            }

            var indent = perRowScope ? "                                        " : "                                    ";

            // Build the call argument list in declaration order, by the same rule
            // buildArgsFromColumns uses: a header match, then the step text's own captures
            // positionally for the parameters no column names (issue #122), then injection.
            var callArgs = new List<(string Name, string? Expression)>();
            var vi = 0;
            foreach (var p in method.Parameters)
            {
                if (p.IsOut)
                {
                    callArgs.Add((p.Name, compareOutputs ? $"out dt{r}__{p.Name}" : "out _"));
                    continue;
                }

                var idx = headers.FindIndex(h => string.Equals(h, p.ColumnName, StringComparison.OrdinalIgnoreCase));

                // Explicit attributes beat a header match; convention injection only applies
                // to parameters no column supplies.
                if (p.IsExplicitlyInjected || (p.IsInjected && idx < 0))
                    callArgs.Add((p.Name, injectionExpression(p, rowScopeProvider)));
                else if (idx >= 0 && idx < row.Count)
                    callArgs.Add((p.Name, CucumberExpressionParser.ToCSharpLiteral(row[idx], p)));
                else if (vi < values.Count)
                    callArgs.Add((p.Name, CucumberExpressionParser.ToCSharpLiteral(values[vi++], p)));
                else if (p.IsOptional)
                    // The column was left out and the parameter declares what to do about it, so
                    // the argument is omitted and C# applies the default the fixture wrote.
                    callArgs.Add((p.Name, null));
                else
                    callArgs.Add((p.Name, $"default({p.QualifiedType})"));
            }

            var argList = argumentList(callArgs);
            if (returnColumn != null)
                sb.AppendLine($"{indent}dt{r}__ret = {awaitKw}{target}.{method.MethodName}({argList});");
            else
                sb.AppendLine($"{indent}{awaitKw}{target}.{method.MethodName}({argList});");

            if (perRowScope)
                sb.AppendLine("                                    }");

            // The compared columns, inside the try: they read what the call produced.
            foreach (var header in headers.Where(IsCompared))
            {
                var value = Cell(header);
                var param = FindParam(header);

                if (param != null && param.IsOut)
                {
                    sb.AppendLine($"                                    cells__.Add(CellCheck.For<{param.QualifiedType}>(\"{escapeString(header)}\", dt{r}__{param.Name}, \"{escapeString(value)}\", {opts}, {r}));");
                }
                else
                {
                    sb.AppendLine($"                                    cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(header)}\", dt{r}__ret, \"{escapeString(value)}\", {opts}, {r}));");
                }
            }

            sb.AppendLine("                                }");
            sb.AppendLine("                                catch (global::System.Exception ex__) when (DecisionTableComparer.IsRowFailure(ex__))");
            sb.AppendLine("                                {");
            sb.AppendLine($"                                    cells__.Add(DecisionTableComparer.RowError({r}, ex__));");
            sb.AppendLine("                                }");

            // The input columns, outside the try: their values are what the document says, known
            // whether or not the row ran, so a row that threw still shows what it was given.
            foreach (var header in headers.Where(h => !IsCompared(h)))
            {
                sb.AppendLine($"                                cells__.Add(new CellResult(\"{escapeString(header)}\", ResultStatus.ok, \"{escapeString(Cell(header))}\") {{ RowIndex = {r} }});");
            }

            sb.AppendLine("                            }");
        }

        sb.AppendLine("                        }");
        sb.AppendLine("                        finally");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            DecisionTableComparer.Apply(result, new[] {{ {columnsLiteral} }}, cells__);");
        sb.AppendLine("                        }");
        if (!method.IsAsync)
            sb.AppendLine("                        return Task.CompletedTask;");
        var binding = bindingInitializer(declaringType, method.MethodName, method.Expression,
            compareOutputs
                ? bindingArgsForDecisionTable(method, headers, returnColumn)
                : bindingArgsFromColumns(method.Parameters, values, headers));
        sb.AppendLine($"                    }}) {binding});");
    }

    /// <summary>
    /// Emit a [WaitFor] step: the step's success criterion (return/out comparison, a [Check]
    /// bool, or a void no-throw action) is retried via WaitForRunner until it converges or
    /// times out.
    /// </summary>
    private static void emitWaitForStep(StringBuilder sb, StepInfo step, StepMethodInfo method,
        string stepId, string stepKind, List<string> values, bool compareReturn, bool isComparison,
        string target, string ctxStmt, string binding, string scopeStmt = "", string? scopeProvider = null)
    {
        var timeout = method.WaitForTimeoutMs!.Value;
        var poll = method.WaitForPollMs;
        var opts = emitCheckOptions(method);
        var awaitKw = method.IsAsync ? "await " : "";

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        async (ctx, result, ct) =>");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        await WaitForRunner.Poll(result, {timeout}, {poll}, async (pollCt) =>");
        sb.AppendLine("                        {");
        if (!method.IsAsync)
            sb.AppendLine("                            await Task.CompletedTask;");
        if (ctxStmt.Length > 0) sb.AppendLine($"                            {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                            {scopeStmt.TrimEnd()}");

        if (isComparison)
        {
            var callArgs = new List<string>();
            var outCompares = new List<(string Name, string Local, string Type, string Expected)>();
            var vi = 0;
            foreach (var p in method.Parameters)
            {
                if (p.IsInjected)
                {
                    callArgs.Add(injectionExpression(p, scopeProvider));
                    continue;
                }

                var capture = vi < values.Count ? values[vi] : "";
                vi++;

                if (p.IsOut)
                {
                    var local = "out__" + p.Name;
                    sb.AppendLine($"                            {p.QualifiedType} {local};");
                    callArgs.Add($"out {local}");
                    outCompares.Add((p.Name, local, p.QualifiedType, capture));
                }
                else
                {
                    callArgs.Add(CucumberExpressionParser.ToCSharpLiteral(capture, p));
                }
            }

            var argList = string.Join(", ", callArgs);
            if (compareReturn)
                sb.AppendLine($"                            var actual__ret = {awaitKw}{target}.{method.MethodName}({argList});");
            else
                sb.AppendLine($"                            {awaitKw}{target}.{method.MethodName}({argList});");

            sb.AppendLine("                            var cells__ = new System.Collections.Generic.List<CellResult>();");
            foreach (var (name, local, type, expected) in outCompares)
                sb.AppendLine($"                            cells__.Add(CellCheck.For<{type}>(\"{escapeString(name)}\", {local}, \"{escapeString(expected)}\", {opts}));");

            if (compareReturn)
            {
                var col = method.ReturnColumn ?? "result";
                var retExpected = values[valueParamCount(method)];
                sb.AppendLine($"                            cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(col)}\", actual__ret, \"{escapeString(retExpected)}\", {opts}));");
            }

            sb.AppendLine("                            return new WaitAttempt(cells__.TrueForAll(c => c.Status == ResultStatus.success), cells__.ToArray());");
        }
        else if (method.IsFact)
        {
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            sb.AppendLine($"                            var ok__ = {awaitKw}{target}.{method.MethodName}({args});");
            sb.AppendLine("                            var cell__ = new CellResult(\"result\", ok__ ? ResultStatus.success : ResultStatus.failed) { Expected = \"true\", Actual = ok__ ? \"true\" : \"false\" };");
            sb.AppendLine("                            return new WaitAttempt(ok__, new[] { cell__ });");
        }
        else
        {
            // void / no-throw action
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            sb.AppendLine($"                            {awaitKw}{target}.{method.MethodName}({args});");
            sb.AppendLine("                            return new WaitAttempt(true, System.Array.Empty<CellResult>());");
        }

        sb.AppendLine("                        }, ct, ctx);");
        sb.AppendLine($"                    }}) {binding});");
    }

    // --- Step binding metadata (issue #208) ---
    //
    // The matcher already decided which method a step runs and where every parameter's value
    // comes from; these helpers write that decision down as a StepBinding initializer so the
    // preview command can show it without executing anything. Each builder MIRRORS the
    // corresponding arg builder's rules — the description must never disagree with the call.

    /// <summary>The <c>{ Binding = ... }</c> object initializer emitted after a step's ctor args.</summary>
    private static string bindingInitializer(string declaringType, string method, string expression,
        List<string> argLiterals)
    {
        var args = argLiterals.Count == 0
            ? "System.Array.Empty<global::Bobcat.Runtime.StepBindingArgument>()"
            : "new global::Bobcat.Runtime.StepBindingArgument[] { " + string.Join(", ", argLiterals) + " }";

        return "{ Binding = new global::Bobcat.Runtime.StepBinding(" +
               $"\"{escapeString(declaringType)}\", \"{escapeString(method)}\", \"{escapeString(expression)}\", {args}) }}";
    }

    private static string bindingArgLiteral(string name, string value, string source)
        => $"new global::Bobcat.Runtime.StepBindingArgument(\"{escapeString(name)}\", \"{escapeString(value)}\", " +
           $"global::Bobcat.Runtime.StepArgumentSource.{source})";

    /// <summary>Mirrors <see cref="buildArgsFromCaptures"/> (and the comparison/wait-for loops,
    /// which additionally consume captures as <c>out</c>-parameter expected values).</summary>
    private static List<string> bindingArgsFromCaptures(List<ParameterInfo> parameters, List<string> values,
        string? docString)
    {
        var args = new List<string>();
        var vi = 0;
        var docStringAvailable = docString != null;
        foreach (var param in parameters)
        {
            if (param.Binding == ParameterBinding.Table)
            {
                args.Add(bindingArgLiteral(param.Name, param.Type, "Table"));
            }
            else if (param.IsInjected)
            {
                args.Add(bindingArgLiteral(param.Name, param.Type, "Service"));
            }
            else if (param.IsOut)
            {
                var capture = vi < values.Count ? values[vi] : "";
                vi++;
                args.Add(bindingArgLiteral(param.Name, capture, "Expected"));
            }
            else if (vi < values.Count)
            {
                args.Add(bindingArgLiteral(param.Name, values[vi], "Capture"));
                vi++;
            }
            else if (docStringAvailable && param.Type == "string")
            {
                args.Add(bindingArgLiteral(param.Name, "doc string", "DocString"));
                docStringAvailable = false;
            }
            else
            {
                args.Add(bindingArgLiteral(param.Name, "", "Default"));
            }
        }

        return args;
    }

    /// <summary>Adds the compared-return pseudo-argument a comparison step carries.</summary>
    private static List<string> withReturnCompare(List<string> args, StepMethodInfo method, List<string> values)
    {
        var col = method.ReturnColumn ?? "result";
        var expected = valueParamCount(method) < values.Count ? values[valueParamCount(method)] : "";
        args.Add(bindingArgLiteral(col, expected, "Expected"));
        return args;
    }

    /// <summary>Adds one compared pseudo-argument per tuple element a comparison step returns.</summary>
    private static List<string> withTupleCompare(List<string> args, StepMethodInfo method, List<string> values)
    {
        var first = valueParamCount(method);
        for (var i = 0; i < method.ReturnTupleElements.Count; i++)
        {
            var expected = first + i < values.Count ? values[first + i] : "";
            args.Add(bindingArgLiteral(method.ReturnTupleElements[i].Name, expected, "Expected"));
        }

        return args;
    }

    /// <summary>Mirrors <see cref="buildArgsFromColumns"/>: header match beats convention
    /// injection, explicit injection beats a header, leftover captures bind positionally.</summary>
    private static List<string> bindingArgsFromColumns(List<ParameterInfo> parameters, List<string> values,
        List<string> headers)
    {
        var args = new List<string>();
        var vi = 0;
        foreach (var param in parameters)
        {
            var colIndex = headers.FindIndex(h =>
                string.Equals(h, param.ColumnName, StringComparison.OrdinalIgnoreCase));

            if (param.IsExplicitlyInjected || (param.IsInjected && colIndex < 0))
            {
                args.Add(bindingArgLiteral(param.Name, param.Type, "Service"));
            }
            else if (colIndex >= 0)
            {
                args.Add(bindingArgLiteral(param.Name, headers[colIndex], "TableColumn"));
            }
            else if (vi < values.Count)
            {
                args.Add(bindingArgLiteral(param.Name, values[vi], "Capture"));
                vi++;
            }
            else
            {
                args.Add(bindingArgLiteral(param.Name, "", "Default"));
            }
        }

        return args;
    }

    /// <summary>Mirrors <see cref="emitRowTableStep"/>'s column classification: out
    /// parameters and the return column are expected outputs, headers supply inputs.</summary>
    private static List<string> bindingArgsForDecisionTable(StepMethodInfo method, List<string> headers,
        string? returnColumn)
    {
        var args = new List<string>();
        foreach (var param in method.Parameters)
        {
            var colIndex = headers.FindIndex(h =>
                string.Equals(h, param.ColumnName, StringComparison.OrdinalIgnoreCase));

            if (param.IsOut)
            {
                args.Add(bindingArgLiteral(param.Name, colIndex >= 0 ? headers[colIndex] : param.Name, "Expected"));
            }
            else if (param.IsExplicitlyInjected || (param.IsInjected && colIndex < 0))
            {
                args.Add(bindingArgLiteral(param.Name, param.Type, "Service"));
            }
            else if (colIndex >= 0)
            {
                args.Add(bindingArgLiteral(param.Name, headers[colIndex], "TableColumn"));
            }
            else
            {
                args.Add(bindingArgLiteral(param.Name, "", "Default"));
            }
        }

        if (returnColumn != null)
        {
            args.Add(bindingArgLiteral(returnColumn, returnColumn, "Expected"));
        }

        return args;
    }

    private static string emitCheckOptions(StepMethodInfo method)
    {
        if (method.ApproxTolerance.HasValue)
            return $"new CheckOptions {{ Tolerance = {method.ApproxTolerance.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)} }}";
        return "null";
    }

    private static string buildSentenceArgs(StepMethodInfo method, List<string> values, string? docString = null,
        string? scopeProvider = null, string? tableLiteral = null)
        => buildArgsFromCaptures(method.Parameters, values, docString, scopeProvider, tableLiteral);

    /// <summary>
    /// The C# expression building the step's trailing data table as a <c>Bobcat.StepTable</c>,
    /// or <c>null</c> when the step has none. Bound to a <c>StepTable</c> parameter.
    /// </summary>
    private static string? tableLiteral(StepInfo step)
    {
        if (step.TableHeaders == null || step.TableRows == null) return null;

        var headers = string.Join(", ", step.TableHeaders.Select(h => $"\"{escapeString(h)}\""));
        var rows = string.Join(", ", step.TableRows.Select(r =>
            "new string[] { " + string.Join(", ", r.Select(c => $"\"{escapeString(c)}\"")) + " }"));

        return $"new global::Bobcat.StepTable(new string[] {{ {headers} }}, new string[][] {{ {rows} }})";
    }

    /// <summary>
    /// Bind parameters to Cucumber captures positionally, skipping injected ones. A trailing
    /// DocString fills the first uncovered string parameter; a <c>StepTable</c> parameter takes
    /// <paramref name="tableLiteral"/> (or null when the step carries no table).
    /// </summary>
    private static string buildArgsFromCaptures(List<ParameterInfo> parameters, List<string> values,
        string? docString, string? scopeProvider, string? tableLiteral = null)
    {
        if (parameters.Count == 0) return "";

        var args = new List<(string Name, string? Expression)>();
        var vi = 0;
        foreach (var param in parameters)
        {
            if (param.Binding == ParameterBinding.Table)
            {
                args.Add((param.Name, tableLiteral ?? "null"));
            }
            else if (param.IsInjected)
            {
                args.Add((param.Name, injectionExpression(param, scopeProvider)));
            }
            else if (vi < values.Count)
            {
                args.Add((param.Name, CucumberExpressionParser.ToCSharpLiteral(values[vi], param)));
                vi++;
            }
            else if (docString != null && param.Type == "string")
            {
                // A DocString fills the trailing string parameter not covered by captures.
                args.Add((param.Name, CucumberExpressionParser.ToCSharpLiteral(docString, "string")));
                docString = null;
            }
            else if (param.IsOptional)
            {
                // Nothing in the step supplied it and the parameter says what to do about that.
                args.Add((param.Name, null));
            }
            else
            {
                args.Add((param.Name, $"default({param.QualifiedType})"));
            }
        }

        return argumentList(args);
    }

    private static string buildTableRowArgs(StepMethodInfo method, List<string> values, List<string> headers,
        List<string> row, string? scopeProvider = null)
        => buildArgsFromColumns(method.Parameters, values, headers, row, scopeProvider);

    /// <summary>
    /// Bind parameters to a table row by header name, the Cucumber captures from the step text
    /// positionally to the parameters no header names, and injection for the rest. A step that
    /// is both a <c>[Table]</c> step and has a capture in its text (<c>these steps ran in
    /// {string}</c>) therefore receives the matched text, not <c>default</c> (issue #122).
    /// </summary>
    private static string buildArgsFromColumns(List<ParameterInfo> parameters, List<string> values,
        List<string> headers, List<string> row, string? scopeProvider)
    {
        var args = new List<(string Name, string? Expression)>();
        var vi = 0;
        foreach (var param in parameters)
        {
            // A header match wins over convention-based injection; [FromScopedService] and
            // friends are the explicit override that wins over a header match.
            var colIndex = headers.FindIndex(h =>
                string.Equals(h, param.ColumnName, StringComparison.OrdinalIgnoreCase));

            if (param.IsExplicitlyInjected || (param.IsInjected && colIndex < 0))
            {
                args.Add((param.Name, injectionExpression(param, scopeProvider)));
            }
            else if (colIndex >= 0 && colIndex < row.Count)
            {
                args.Add((param.Name, CucumberExpressionParser.ToCSharpLiteral(row[colIndex], param)));
            }
            else if (vi < values.Count)
            {
                // No column names this parameter, so it consumes the next capture from the
                // step text — the same positional rule a non-table step binds by.
                args.Add((param.Name, CucumberExpressionParser.ToCSharpLiteral(values[vi], param)));
                vi++;
            }
            else if (param.IsOptional)
            {
                // An optional column: the argument is omitted and C# applies the parameter's own
                // default. Before this it was passed default(T), so a fixture that wrote
                // `string currency = "USD"` saw null instead.
                args.Add((param.Name, null));
            }
            else
            {
                args.Add((param.Name, $"default({param.QualifiedType})"));
            }
        }

        return argumentList(args);
    }

    /// <summary>
    /// An argument list with the omitted arguments left out. Positional while nothing is skipped;
    /// once something is, every argument is named, because a gap cannot be expressed positionally.
    /// </summary>
    private static string argumentList(List<(string Name, string? Expression)> args)
    {
        var supplied = args.Where(a => a.Expression != null).ToList();
        if (supplied.Count == args.Count)
            return string.Join(", ", supplied.Select(a => a.Expression));

        return string.Join(", ", supplied.Select(a => $"{escapeIdentifier(a.Name)}: {a.Expression}"));
    }

    /// <summary>A parameter name as a named argument: escaped when it is a C# keyword.</summary>
    private static string escapeIdentifier(string name)
        => CSharpKeywords.Contains(name) ? "@" + name : name;

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    /// <summary>
    /// The <c>new Module(...)</c> expression for a grammar module instance (issue #212 phase 2):
    /// the <c>[IncludeGrammars]</c> literals plus scenario-scope resolutions, all as named
    /// arguments so omitted trailing optional parameters leave no illegal positional gap.
    /// </summary>
    private static string moduleConstruction(ModuleInfo? module, string fallbackFqn)
    {
        if (module == null || module.ConstructionParameters.Count == 0)
            return $"new {module?.FullyQualifiedName ?? fallbackFqn}()";

        var args = module.ConstructionParameters.Select(arg => arg.Literal != null
            ? $"{arg.Parameter.Name}: {arg.Literal}"
            : $"{arg.Parameter.Name}: {injectionExpression(arg.Parameter, null)}");

        return $"new {module.FullyQualifiedName}({string.Join(", ", args)})";
    }

    /// <summary>
    /// The C# expression that supplies an injected parameter. Scoped resolutions go through
    /// <paramref name="scopeProvider"/> when a <c>[NewScope]</c>/<c>[ScopePerRow]</c> child
    /// scope is open, otherwise through the scenario scope on the host resource.
    /// </summary>
    private static string injectionExpression(ParameterInfo p, string? scopeProvider)
    {
        var resource = p.ResourceName == null ? "null" : $"\"{escapeString(p.ResourceName)}\"";

        switch (p.Binding)
        {
            case ParameterBinding.StepContext:
                return "ctx";

            case ParameterBinding.Table:
                // Only sentence, Check, WaitFor and set-verification steps carry the table through
                // buildArgsFromCaptures; anywhere else (per-row [Table] calls, decision tables,
                // hooks) there is no whole table to hand over.
                return "null";

            case ParameterBinding.Resource:
                return $"ctx.GetResource<{p.QualifiedType}>({resource})";

            case ParameterBinding.RootService:
                return $"Bobcat.Runtime.HostResourceExtensions.GetRootService<{p.QualifiedType}>(ctx, {resource})";

            case ParameterBinding.KeyedService:
                var key = p.ServiceKey == null ? "null" : $"\"{escapeString(p.ServiceKey)}\"";
                return scopeProvider != null
                    ? $"Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<{p.QualifiedType}>({scopeProvider}, {key})"
                    : $"Bobcat.Runtime.HostResourceExtensions.GetKeyedHostService<{p.QualifiedType}>(ctx, {key}, {resource})";

            default:
                return scopeProvider != null
                    ? $"Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{p.QualifiedType}>({scopeProvider})"
                    : $"Bobcat.Runtime.HostResourceExtensions.GetHostService<{p.QualifiedType}>(ctx, {resource})";
        }
    }

    /// <summary>Number of parameters that consume a Cucumber capture.</summary>
    private static int valueParamCount(StepMethodInfo method)
    {
        var count = 0;
        foreach (var p in method.Parameters) if (!p.IsInjected) count++;
        return count;
    }

    /// <summary>The expression that opens a <c>[NewScope]</c>/<c>[ScopePerRow]</c> child scope.</summary>
    private static string childScopeExpression(StepMethodInfo method)
    {
        var resource = method.ScopeResourceName == null
            ? "null"
            : $"\"{escapeString(method.ScopeResourceName)}\"";
        return $"Bobcat.Runtime.HostResourceExtensions.CreateChildScope(ctx, {resource})";
    }

    /// <summary>The <c>using var</c> declaration that opens a child scope for a whole step.</summary>
    private static string childScopeStatement(StepMethodInfo method, string local)
        => $"using var {local} = {childScopeExpression(method)};";

    public static string SanitizeIdentifier(string text)
    {
        var sb = new StringBuilder();
        foreach (var c in text)
        {
            if (char.IsLetterOrDigit(c))
                sb.Append(c);
            else if (c == ' ')
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static string escapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

public class MatchedScenario
{
    public ScenarioInfo Scenario { get; set; } = null!;
    public List<MatchedStep> Steps { get; set; } = new();
}

public class MatchedStep
{
    public StepInfo Step { get; set; } = null!;

    /// <summary>Set when the step matched a fixture/module step method.</summary>
    public StepMatcher.MatchResult? Match { get; set; }

    /// <summary>Set when the step matched a <c>[TableGrammar]</c> class instead.</summary>
    public StepMatcher.TableGrammarMatch? GrammarMatch { get; set; }
}
