using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bobcat.Generators;

/// <summary>
/// Generates C# source code from matched features.
/// Output targets the Bobcat runtime types (FeatureDefinition, DelegateExecutionStep, etc).
/// </summary>
public static class CodeEmitter
{
    public static string EmitFeature(FeatureInfo feature, FixtureInfo fixture, List<MatchedScenario> scenarios)
    {
        var safeClassName = SanitizeIdentifier(feature.Title) + "_Feature";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Bobcat;");
        sb.AppendLine("using Bobcat.Engine;");
        sb.AppendLine("using Bobcat.Engine.Verification;");
        sb.AppendLine("using Bobcat.Runtime;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {fixture.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"[System.CodeDom.Compiler.GeneratedCode(\"Bobcat.Generators\", \"1.0\")]");
        sb.AppendLine($"public static class {safeClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static FeatureDefinition Define()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new FeatureDefinition(");
        sb.AppendLine($"            \"{escapeString(feature.Title)}\",");
        sb.AppendLine($"            typeof({fixture.FullyQualifiedName}),");
        sb.AppendLine("            new ScenarioDefinition[]");
        sb.AppendLine("            {");

        foreach (var scenario in scenarios)
        {
            emitScenario(sb, scenario, fixture);
        }

        sb.AppendLine("            })");
        sb.AppendLine("        {");
        if (feature.Tags.Count > 0)
            sb.AppendLine($"            Tags = new[] {{ {string.Join(", ", feature.Tags.Select(t => $"\"{escapeString(t)}\""))} }},");
        if (feature.Description != null)
            sb.AppendLine($"            Description = \"{escapeString(feature.Description)}\",");
        emitHook(sb, fixture, HookKind.BeforeEach);
        emitHook(sb, fixture, HookKind.AfterEach);
        emitHook(sb, fixture, HookKind.BeforeAll);
        emitHook(sb, fixture, HookKind.AfterAll);
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emit the discovered lifecycle hooks of one kind as a single delegate. Parameters are
    /// resolved by type at compile time, exactly like step arguments — no reflection.
    /// </summary>
    private static void emitHook(StringBuilder sb, FixtureInfo fixture, HookKind kind)
    {
        var hooks = fixture.HooksOf(kind).ToList();
        if (hooks.Count == 0) return;

        var featureLevel = kind == HookKind.BeforeAll || kind == HookKind.AfterAll;
        var signature = featureLevel ? "async (ctx) =>" : "async (fixture, ctx) =>";

        sb.AppendLine($"            {kind} = {signature}");
        sb.AppendLine("            {");

        if (!featureLevel)
            sb.AppendLine($"                var f = ({fixture.FullyQualifiedName})fixture;");

        // Keeps the lambda legally async even when every hook is synchronous.
        sb.AppendLine("                await Task.CompletedTask;");

        foreach (var hook in hooks)
        {
            var target = featureLevel ? fixture.FullyQualifiedName : "f";
            var args = string.Join(", ", hook.Parameters.Select(p => injectionExpression(p, null)));
            var awaitKw = hook.IsAsync ? "await " : "";
            sb.AppendLine($"                {awaitKw}{target}.{hook.MethodName}({args});");
        }

        sb.AppendLine("            },");
    }

    private static void emitScenario(StringBuilder sb, MatchedScenario scenario, FixtureInfo fixture)
    {
        var tags = scenario.Scenario.Tags;
        var tagsArray = tags.Count > 0
            ? "new[] { " + string.Join(", ", tags.Select(t => $"\"{escapeString(t)}\"")) + " }"
            : "Array.Empty<string>()";

        sb.AppendLine($"                new ScenarioDefinition(");
        sb.AppendLine($"                    \"{escapeString(scenario.Scenario.Title)}\",");
        sb.AppendLine($"                    {tagsArray},");
        sb.AppendLine($"                    (fixture, plan) =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var f = ({fixture.FullyQualifiedName})fixture;");

        // Declare instances for the grammar modules used by this scenario (one per scenario).
        var usedModules = scenario.Steps
            .Where(s => s.Match != null)
            .Select(s => s.Match!.Method.DeclaringModule)
            .Where(m => m != null)
            .Distinct()
            .ToList();
        foreach (var moduleFqn in usedModules)
        {
            sb.AppendLine($"                    var {fixture.ModuleLocal(moduleFqn!)} = new {moduleFqn}();");
        }

        foreach (var matched in scenario.Steps)
        {
            emitStep(sb, matched, fixture);
        }

        sb.AppendLine("                }),");
    }

    private static void emitStep(StringBuilder sb, MatchedStep matched, FixtureInfo fixture)
    {
        var step = matched.Step;

        var stepKind = step.ResolvedKeyword.Trim() switch
        {
            "Given" => "StepKind.Given",
            "When" => "StepKind.When",
            "Then" => "StepKind.Then",
            _ => "StepKind.Then"
        };

        if (matched.GrammarMatch != null)
        {
            emitTableGrammarStep(sb, step, matched.GrammarMatch, stepKind);
            return;
        }

        var method = matched.Match!.Method;
        var values = matched.Match.ExtractedValues;

        var stepId = method.MethodName;

        // Call routing: the fixture itself ("f") or a per-scenario grammar-module instance.
        var target = method.DeclaringModule == null ? "f" : fixture.ModuleLocal(method.DeclaringModule);
        var module = method.DeclaringModule == null ? null : fixture.FindModule(method.DeclaringModule);
        // A module that inherits Fixture receives the step context before its method runs.
        var ctxStmt = module is { IsFixture: true } ? $"{target}.Context = ctx; " : "";

        // Does this comparison have a return-value capture? (one capture beyond the value params)
        var compareReturn = method.HasReturnValue && method.StepKind == "Then"
            && values.Count == valueParamCount(method) + 1;
        var isComparison = !method.IsTable && !method.IsSetVerification && !method.IsDecisionTable
            && (method.OutParameters.Count > 0 || compareReturn);

        // [NewScope] — this step's injected services come from a child scope nested under
        // the scenario scope, disposed when the step finishes.
        var scopeStmt = method.NewScope ? childScopeStatement(method, "__sc") + " " : "";
        var scopeProvider = method.NewScope ? "__sc.ServiceProvider" : null;

        if (method.IsDecisionTable && step.TableRows != null && step.TableHeaders != null)
        {
            emitDecisionTableStep(sb, step, method, stepId, target, ctxStmt, scopeStmt, scopeProvider);
        }
        else if (method.IsTable && step.TableRows != null && step.TableHeaders != null)
        {
            // Table grammar — emit one step per row. Each row already runs in its own lambda,
            // so [ScopePerRow] and [NewScope] mean the same thing here.
            var rowScope = method.ScopePerRow || method.NewScope;
            var rowScopeStmt = rowScope ? childScopeStatement(method, "__sc") + " " : "";
            var rowScopeProvider = rowScope ? "__sc.ServiceProvider" : null;

            for (var rowIdx = 0; rowIdx < step.TableRows.Count; rowIdx++)
            {
                var row = step.TableRows[rowIdx];
                var headers = step.TableHeaders;

                var args = buildTableRowArgs(method, headers, row, rowScopeProvider);
                var rowStepId = $"{stepId}.row{rowIdx + 1}";
                var awaitRow = method.IsAsync ? "await " : "";

                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{escapeString(rowStepId)}\",");
                sb.AppendLine($"                        {stepKind},");
                sb.AppendLine($"                        \"{escapeString(step.Text)} (row {rowIdx + 1})\",");
                if (method.IsAsync)
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {ctxStmt}{rowScopeStmt}{awaitRow}{target}.{method.MethodName}({args}); }}));");
                else
                    sb.AppendLine($"                        (ctx, result, ct) => {{ {ctxStmt}{rowScopeStmt}{target}.{method.MethodName}({args}); return Task.CompletedTask; }}));");
            }
        }
        else if (method.IsSetVerification && step.TableRows != null && step.TableHeaders != null)
        {
            // Set verification — emit comparison code
            emitSetVerificationStep(sb, step, method, stepId, stepKind, target, ctxStmt, values);
        }
        else if (method.WaitForTimeoutMs.HasValue)
        {
            emitWaitForStep(sb, step, method, stepId, stepKind, values, compareReturn, isComparison, target, ctxStmt,
                scopeStmt, scopeProvider);
        }
        else if (isComparison)
        {
            emitComparisonStep(sb, step, method, stepId, stepKind, values, compareReturn, target, ctxStmt,
                scopeStmt, scopeProvider);
        }
        else
        {
            // Regular sentence step
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            var awaitPrefix = method.IsAsync ? "await " : "";
            var returnSuffix = method.IsAsync ? "" : " return Task.CompletedTask;";

            if (method.StepKind == "Check")
            {
                // Check (bool return) — assertion failure, not critical
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{escapeString(stepId)}\",");
                sb.AppendLine($"                        StepKind.Then,");
                sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}if (!await {target}.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); }}));");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}if (!{target}.{method.MethodName}({args})) result.MarkFailed(); else result.MarkSuccess(); return Task.CompletedTask; }}));");
                }
            }
            else
            {
                sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
                sb.AppendLine($"                        \"{escapeString(stepId)}\",");
                sb.AppendLine($"                        {stepKind},");
                sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
                if (method.IsAsync)
                {
                    sb.AppendLine($"                        async (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}{awaitPrefix}{target}.{method.MethodName}({args}); }}));");
                }
                else
                {
                    sb.AppendLine($"                        (ctx, result, ct) => {{ {ctxStmt}{scopeStmt}{target}.{method.MethodName}({args});{returnSuffix} }}));");
                }
            }
        }
    }

    /// <summary>
    /// Emit a <c>[TableGrammar]</c> envelope: a fresh grammar instance, <c>Before</c> once,
    /// then one <c>Row</c> call per table row, then <c>After</c> in a <c>finally</c> so it runs
    /// even when <c>Before</c> or a row threw.
    /// </summary>
    private static void emitTableGrammarStep(StringBuilder sb, StepInfo step,
        StepMatcher.TableGrammarMatch match, string stepKind)
    {
        var grammar = match.Grammar;
        var row = grammar.Row;
        var headers = step.TableHeaders!;
        var rows = step.TableRows!;
        var values = match.ExtractedValues;

        // Columns the Row method consumes as inputs. An explicitly-injected parameter never
        // claims a column, so [FromScopedService] on a parameter named like a header still
        // leaves that header available as an expected value.
        var boundHeaders = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in row?.Parameters ?? new List<ParameterInfo>())
        {
            if (p.IsExplicitlyInjected) continue;
            var header = headers.FirstOrDefault(h => string.Equals(h, p.Name, StringComparison.OrdinalIgnoreCase));
            if (header != null) boundHeaders.Add(header);
        }

        var leftover = headers.Where(h => !boundHeaders.Contains(h)).ToList();

        // Decision-table disambiguation: a Row return plus exactly one unbound column means
        // that column is the expected output. WITH a recipe, Row's return is a product to
        // persist instead, so nothing is treated as an expected value.
        var expectedColumn = grammar.HasRecipe
            ? null
            : grammar.RowExpectedColumn != null
                ? headers.FirstOrDefault(h => string.Equals(h, grammar.RowExpectedColumn, StringComparison.OrdinalIgnoreCase))
                : (row is { HasReturnValue: true } && leftover.Count == 1 ? leftover[0] : null);

        var opts = grammar.ApproxTolerance.HasValue
            ? $"new CheckOptions {{ Tolerance = {grammar.ApproxTolerance.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)} }}"
            : "null";

        var columnsLiteral = string.Join(", ", headers.Select(h => $"\"{escapeString(h)}\""));

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(grammar.ClassName)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        async (ctx, result, ct) =>");
        sb.AppendLine("                    {");
        // Keeps the lambda legally async when every envelope method is synchronous.
        sb.AppendLine("                        await Task.CompletedTask;");
        // Fresh instance per execution, so Before's session and After's save share fields.
        sb.AppendLine($"                        var g__ = new {grammar.FullyQualifiedName}();");
        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        if (grammar.HasRecipe)
        {
            // The one runtime-resolved piece: the recipe's behavior lives in the extension
            // package (Marten/EF), which the netstandard2.0 generator must not reference.
            sb.AppendLine($"                        await using var behavior__ = Bobcat.Runtime.GrammarBehaviors.Resolve(typeof({grammar.FullyQualifiedName}));");
        }

        sb.AppendLine("                        try");
        sb.AppendLine("                        {");

        if (grammar.HasRecipe)
            sb.AppendLine("                            await behavior__.Open(ctx);");

        if (grammar.Before != null)
        {
            var beforeArgs = buildArgsFromCaptures(grammar.Before.Parameters, values, null, null);
            var awaitBefore = grammar.Before.IsAsync ? "await " : "";
            sb.AppendLine($"                            {awaitBefore}g__.{grammar.Before.MethodName}({beforeArgs});");
        }

        var awaitRow = row is { IsAsync: true } ? "await " : "";

        for (var r = 0; r < rows.Count; r++)
        {
            var rowCells = rows[r];
            sb.AppendLine($"                            // row {r + 1}");
            sb.AppendLine("                            {");
            // Row-level progress: to the executor the whole table is one step, so without this
            // a 200-row grammar is the least observable thing in a suite. Message-less on
            // purpose — see StepUpdate.ForRow.
            sb.AppendLine($"                                ctx.ReportProgress(global::Bobcat.Engine.StepUpdate.ForRow({r + 1}, {rows.Count}));");

            var rowScopeProvider = grammar.ScopePerRow ? $"__sc{r}.ServiceProvider" : null;
            if (grammar.ScopePerRow)
            {
                var resource = grammar.ScopeResourceName == null
                    ? "null"
                    : $"\"{escapeString(grammar.ScopeResourceName)}\"";
                sb.AppendLine($"                                using var __sc{r} = Bobcat.Runtime.HostResourceExtensions.CreateChildScope(ctx, {resource});");
            }

            if (grammar.HasRecipe)
            {
                // With a recipe, each row produces a product that the behavior persists.
                // A hand-written Row is the override for custom construction; without one,
                // columns bind straight to the entity's constructor or settable properties.
                var product = row != null
                    ? $"{awaitRow}g__.{row.MethodName}({buildArgsFromColumns(row.Parameters, headers, rowCells, rowScopeProvider)})"
                    : buildEntityFromColumns(grammar, headers, rowCells);

                sb.AppendLine($"                                var product{r}__ = {product};");
                sb.AppendLine($"                                await behavior__.Row(product{r}__);");
            }
            else if (expectedColumn != null)
            {
                var rowArgs = buildArgsFromColumns(row!.Parameters, headers, rowCells, rowScopeProvider);
                sb.AppendLine($"                                var row{r}__ = {awaitRow}g__.{row.MethodName}({rowArgs});");
            }
            else
            {
                var rowArgs = buildArgsFromColumns(row!.Parameters, headers, rowCells, rowScopeProvider);
                sb.AppendLine($"                                {awaitRow}g__.{row.MethodName}({rowArgs});");
            }

            foreach (var header in headers)
            {
                var idx = headers.FindIndex(h => string.Equals(h, header, StringComparison.OrdinalIgnoreCase));
                var value = idx >= 0 && idx < rowCells.Count ? rowCells[idx] : "";

                if (expectedColumn != null && string.Equals(header, expectedColumn, StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"                                cells__.Add(CellCheck.For<{row!.QualifiedReturnType}>(\"{escapeString(header)}\", row{r}__, \"{escapeString(value)}\", {opts}, {r}));");
                }
                else
                {
                    // Input (or otherwise unconsumed) column — rendered plain.
                    sb.AppendLine($"                                cells__.Add(new CellResult(\"{escapeString(header)}\", ResultStatus.ok, \"{escapeString(value)}\") {{ RowIndex = {r} }});");
                }
            }

            sb.AppendLine("                            }");
        }

        sb.AppendLine("                        }");
        sb.AppendLine("                        finally");
        sb.AppendLine("                        {");

        if (grammar.After != null)
        {
            var afterArgs = buildArgsFromCaptures(grammar.After.Parameters, values, null, null);
            var awaitAfter = grammar.After.IsAsync ? "await " : "";
            sb.AppendLine($"                            {awaitAfter}g__.{grammar.After.MethodName}({afterArgs});");
        }
        else if (!grammar.HasRecipe)
        {
            sb.AppendLine("                            // no After method on this grammar");
        }

        // The recipe closes last, so a hand-written After can still touch the session before
        // the single SaveChangesAsync.
        if (grammar.HasRecipe)
            sb.AppendLine("                            await behavior__.Close();");

        sb.AppendLine("                        }");
        sb.AppendLine($"                        DecisionTableComparer.Apply(result, new[] {{ {columnsLiteral} }}, cells__);");
        sb.AppendLine("                    }));");
    }

    /// <summary>
    /// Convention entity construction: bind columns to the entity's constructor parameters
    /// first (records-friendly), then to settable properties, by header name with the same
    /// type conversion the rest of the generator uses. Emitted as a direct <c>new Customer(...)</c>
    /// — no runtime binder. A hand-written <c>Row</c> is the override for anything this can't do.
    /// </summary>
    private static string buildEntityFromColumns(TableGrammarInfo grammar, List<string> headers, List<string> row)
    {
        var entity = grammar.RecipeEntity!;

        string? Cell(string name)
        {
            var idx = headers.FindIndex(h => string.Equals(h, name, StringComparison.OrdinalIgnoreCase));
            return idx >= 0 && idx < row.Count ? row[idx] : null;
        }

        // Prefer the public constructor that covers the most headers and whose every parameter
        // a column can actually supply.
        List<ParameterInfo>? best = null;
        foreach (var ctor in entity.Constructors)
        {
            var usable = ctor.All(p => p.IsSimpleType && Cell(p.Name) != null);
            if (!usable) continue;
            if (best == null || ctor.Count > best.Count) best = ctor;
        }

        if (best != null)
        {
            var args = best.Select(p =>
                $"{p.Name}: {CucumberExpressionParser.ToCSharpLiteral(Cell(p.Name)!, p.Type)}");
            return $"new {entity.FullyQualifiedName}({string.Join(", ", args)})";
        }

        if (entity.HasParameterlessConstructor)
        {
            var assignments = entity.SettableProperties
                .Where(p => p.IsSimpleType && Cell(p.Name) != null)
                .Select(p => $"{p.Name} = {CucumberExpressionParser.ToCSharpLiteral(Cell(p.Name)!, p.Type)}")
                .ToList();

            if (assignments.Count > 0)
                return $"new {entity.FullyQualifiedName} {{ {string.Join(", ", assignments)} }}";
        }

        throw new InvalidOperationException(
            $"Cannot construct '{entity.Name}' from the columns [{string.Join(", ", headers)}] on grammar " +
            $"'{grammar.ClassName}'. No public constructor's parameters are all supplied by columns, and " +
            "no settable properties match. Write a Row method returning the entity to control construction.");
    }

    private static void emitSetVerificationStep(StringBuilder sb, StepInfo step, StepMethodInfo method, string stepId, string stepKind, string target, string ctxStmt, List<string> values)
    {
        var keyColumns = string.IsNullOrEmpty(method.SetVerificationKeyColumns)
            ? "Array.Empty<string>()"
            : "new[] { " + string.Join(", ", method.SetVerificationKeyColumns.Split(',').Select(k => $"\"{escapeString(k.Trim())}\"")) + " }";

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        StepKind.Then,");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");

        if (method.IsAsync)
        {
            sb.AppendLine($"                        async (ctx, result, ct) =>");
        }
        else
        {
            sb.AppendLine($"                        (ctx, result, ct) =>");
        }

        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");

        // Captures bind positionally as on any sentence step, so "{event} is emitted with:" can
        // hand the method the type it is asked about; a StepTable parameter sees the expected rows.
        var svArgs = buildArgsFromCaptures(method.Parameters, values, step.DocString, null, tableLiteral(step));
        var awaitPrefix = method.IsAsync ? "await " : "";
        sb.AppendLine($"                        var actual = {awaitPrefix}{target}.{method.MethodName}({svArgs});");
        sb.AppendLine($"                        var expected = new List<Dictionary<string, string>>");
        sb.AppendLine("                        {");

        if (step.TableRows != null && step.TableHeaders != null)
        {
            foreach (var row in step.TableRows)
            {
                sb.AppendLine("                            new Dictionary<string, string>");
                sb.AppendLine("                            {");
                for (var i = 0; i < step.TableHeaders.Count && i < row.Count; i++)
                {
                    sb.AppendLine($"                                [\"{escapeString(step.TableHeaders[i])}\"] = \"{escapeString(row[i])}\",");
                }
                sb.AppendLine("                            },");
            }
        }

        sb.AppendLine("                        };");
        sb.AppendLine($"                        SetVerificationComparer.Compare(actual, expected, {keyColumns}, result);");

        if (!method.IsAsync)
        {
            sb.AppendLine("                        return Task.CompletedTask;");
        }

        sb.AppendLine("                    }));");
    }

    /// <summary>
    /// Emit a sentence step that verifies actual-vs-expected via the return value and/or
    /// out parameters. Captures map positionally to parameters; the return-value expected
    /// (when present) is the trailing capture.
    /// </summary>
    private static void emitComparisonStep(StringBuilder sb, StepInfo step, StepMethodInfo method,
        string stepId, string stepKind, List<string> values, bool compareReturn, string target, string ctxStmt,
        string scopeStmt = "", string? scopeProvider = null)
    {
        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        {(method.IsAsync ? "async " : "")}(ctx, result, ct) =>");
        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                        {scopeStmt.TrimEnd()}");

        var callArgs = new List<string>();
        var outCompares = new List<(string Name, string Local, string Type, string Expected)>();
        var vi = 0;
        foreach (var p in method.Parameters)
        {
            if (p.IsInjected)
            {
                callArgs.Add(injectionExpression(p, scopeProvider));
                continue;
            }

            var capture = vi < values.Count ? values[vi] : "";
            vi++;

            if (p.IsOut)
            {
                var local = "out__" + p.Name;
                sb.AppendLine($"                        {p.QualifiedType} {local};");
                callArgs.Add($"out {local}");
                outCompares.Add((p.Name, local, p.QualifiedType, capture));
            }
            else
            {
                callArgs.Add(CucumberExpressionParser.ToCSharpLiteral(capture, p.Type));
            }
        }

        var opts = emitCheckOptions(method);
        var awaitKw = method.IsAsync ? "await " : "";
        var argList = string.Join(", ", callArgs);

        if (compareReturn)
            sb.AppendLine($"                        var actual__ret = {awaitKw}{target}.{method.MethodName}({argList});");
        else
            sb.AppendLine($"                        {awaitKw}{target}.{method.MethodName}({argList});");

        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        foreach (var (name, local, type, expected) in outCompares)
        {
            sb.AppendLine($"                        cells__.Add(CellCheck.For<{type}>(\"{escapeString(name)}\", {local}, \"{escapeString(expected)}\", {opts}));");
        }

        if (compareReturn)
        {
            var col = method.ReturnColumn ?? "result";
            var retExpected = values[valueParamCount(method)];
            sb.AppendLine($"                        cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(col)}\", actual__ret, \"{escapeString(retExpected)}\", {opts}));");
        }

        sb.AppendLine("                        result.MarkCells(cells__.ToArray());");
        sb.AppendLine("                        if (cells__.Exists(c => c.Status != ResultStatus.success)) result.MarkFailed(); else result.MarkSuccess();");

        if (!method.IsAsync)
            sb.AppendLine("                        return Task.CompletedTask;");

        sb.AppendLine("                    }));");
    }

    /// <summary>
    /// Emit a decision table: one method call per row, with input columns supplying
    /// arguments and out/return columns compared as expected outputs. Renders as a grid.
    /// </summary>
    private static void emitDecisionTableStep(StringBuilder sb, StepInfo step, StepMethodInfo method, string stepId,
        string target, string ctxStmt, string scopeStmt = "", string? stepScopeProvider = null)
    {
        var headers = step.TableHeaders!;
        var rows = step.TableRows!;

        // Classify each header: input param, out param, the return value, or unknown (echo).
        var returnColumn = method.ReturnColumn
            ?? (method.HasReturnValue ? method.MethodName : null);

        ParameterInfo? FindParam(string header) =>
            method.Parameters.FirstOrDefault(p =>
                string.Equals(p.Name, header, StringComparison.OrdinalIgnoreCase));

        var opts = emitCheckOptions(method);
        var perRowScope = method.ScopePerRow;

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        StepKind.Then,");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        {(method.IsAsync ? "async " : "")}(ctx, result, ct) =>");
        sb.AppendLine("                    {");
        if (ctxStmt.Length > 0) sb.AppendLine($"                        {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                        {scopeStmt.TrimEnd()}");
        sb.AppendLine("                        var cells__ = new System.Collections.Generic.List<CellResult>();");

        var columnsLiteral = string.Join(", ", headers.Select(h => $"\"{escapeString(h)}\""));
        var awaitKw = method.IsAsync ? "await " : "";

        for (var r = 0; r < rows.Count; r++)
        {
            var row = rows[r];
            string Cell(string header)
            {
                var idx = headers.FindIndex(h => string.Equals(h, header, StringComparison.OrdinalIgnoreCase));
                return idx >= 0 && idx < row.Count ? row[idx] : "";
            }

            sb.AppendLine($"                        // row {r + 1}");

            // Declare out locals (outside any per-row scope block so the cells can read them)
            foreach (var outParam in method.OutParameters)
            {
                sb.AppendLine($"                        {outParam.QualifiedType} dt{r}__{outParam.Name};");
            }
            if (returnColumn != null)
                sb.AppendLine($"                        {method.QualifiedReturnType} dt{r}__ret;");

            // [ScopePerRow] — each row's injected services come from their own child scope.
            var rowScopeLocal = $"__sc{r}";
            var rowScopeProvider = perRowScope ? $"{rowScopeLocal}.ServiceProvider" : stepScopeProvider;
            if (perRowScope)
            {
                sb.AppendLine($"                        using (var {rowScopeLocal} = {childScopeExpression(method)})");
                sb.AppendLine("                        {");
            }

            var indent = perRowScope ? "                            " : "                        ";

            // Build the call argument list in declaration order
            var callArgs = new List<string>();
            foreach (var p in method.Parameters)
            {
                if (p.IsOut)
                {
                    callArgs.Add($"out dt{r}__{p.Name}");
                    continue;
                }

                var idx = headers.FindIndex(h => string.Equals(h, p.Name, StringComparison.OrdinalIgnoreCase));

                // Explicit attributes beat a header match; convention injection only applies
                // to parameters no column supplies.
                if (p.IsExplicitlyInjected || (p.IsInjected && idx < 0))
                    callArgs.Add(injectionExpression(p, rowScopeProvider));
                else if (idx >= 0 && idx < row.Count)
                    callArgs.Add(CucumberExpressionParser.ToCSharpLiteral(row[idx], p.Type));
                else
                    callArgs.Add($"default({p.QualifiedType})");
            }

            var argList = string.Join(", ", callArgs);
            if (returnColumn != null)
                sb.AppendLine($"{indent}dt{r}__ret = {awaitKw}{target}.{method.MethodName}({argList});");
            else
                sb.AppendLine($"{indent}{awaitKw}{target}.{method.MethodName}({argList});");

            if (perRowScope)
                sb.AppendLine("                        }");

            // Emit one cell per header, in header order
            foreach (var header in headers)
            {
                var value = Cell(header);
                var param = FindParam(header);

                if (param != null && param.IsOut)
                {
                    sb.AppendLine($"                        cells__.Add(CellCheck.For<{param.QualifiedType}>(\"{escapeString(header)}\", dt{r}__{param.Name}, \"{escapeString(value)}\", {opts}, {r}));");
                }
                else if (returnColumn != null && string.Equals(header, returnColumn, StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"                        cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(header)}\", dt{r}__ret, \"{escapeString(value)}\", {opts}, {r}));");
                }
                else
                {
                    // input or unknown column — render plain
                    sb.AppendLine($"                        cells__.Add(new CellResult(\"{escapeString(header)}\", ResultStatus.ok, \"{escapeString(value)}\") {{ RowIndex = {r} }});");
                }
            }
        }

        sb.AppendLine($"                        DecisionTableComparer.Apply(result, new[] {{ {columnsLiteral} }}, cells__);");
        if (!method.IsAsync)
            sb.AppendLine("                        return Task.CompletedTask;");
        sb.AppendLine("                    }));");
    }

    /// <summary>
    /// Emit a [WaitFor] step: the step's success criterion (return/out comparison, a [Check]
    /// bool, or a void no-throw action) is retried via WaitForRunner until it converges or
    /// times out.
    /// </summary>
    private static void emitWaitForStep(StringBuilder sb, StepInfo step, StepMethodInfo method,
        string stepId, string stepKind, List<string> values, bool compareReturn, bool isComparison,
        string target, string ctxStmt, string scopeStmt = "", string? scopeProvider = null)
    {
        var timeout = method.WaitForTimeoutMs!.Value;
        var poll = method.WaitForPollMs;
        var opts = emitCheckOptions(method);
        var awaitKw = method.IsAsync ? "await " : "";

        sb.AppendLine($"                    plan.Add(new DelegateExecutionStep(");
        sb.AppendLine($"                        \"{escapeString(stepId)}\",");
        sb.AppendLine($"                        {stepKind},");
        sb.AppendLine($"                        \"{escapeString(step.Text)}\",");
        sb.AppendLine($"                        async (ctx, result, ct) =>");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        await WaitForRunner.Poll(result, {timeout}, {poll}, async (pollCt) =>");
        sb.AppendLine("                        {");
        if (!method.IsAsync)
            sb.AppendLine("                            await Task.CompletedTask;");
        if (ctxStmt.Length > 0) sb.AppendLine($"                            {ctxStmt.TrimEnd()}");
        if (scopeStmt.Length > 0) sb.AppendLine($"                            {scopeStmt.TrimEnd()}");

        if (isComparison)
        {
            var callArgs = new List<string>();
            var outCompares = new List<(string Name, string Local, string Type, string Expected)>();
            var vi = 0;
            foreach (var p in method.Parameters)
            {
                if (p.IsInjected)
                {
                    callArgs.Add(injectionExpression(p, scopeProvider));
                    continue;
                }

                var capture = vi < values.Count ? values[vi] : "";
                vi++;

                if (p.IsOut)
                {
                    var local = "out__" + p.Name;
                    sb.AppendLine($"                            {p.QualifiedType} {local};");
                    callArgs.Add($"out {local}");
                    outCompares.Add((p.Name, local, p.QualifiedType, capture));
                }
                else
                {
                    callArgs.Add(CucumberExpressionParser.ToCSharpLiteral(capture, p.Type));
                }
            }

            var argList = string.Join(", ", callArgs);
            if (compareReturn)
                sb.AppendLine($"                            var actual__ret = {awaitKw}{target}.{method.MethodName}({argList});");
            else
                sb.AppendLine($"                            {awaitKw}{target}.{method.MethodName}({argList});");

            sb.AppendLine("                            var cells__ = new System.Collections.Generic.List<CellResult>();");
            foreach (var (name, local, type, expected) in outCompares)
                sb.AppendLine($"                            cells__.Add(CellCheck.For<{type}>(\"{escapeString(name)}\", {local}, \"{escapeString(expected)}\", {opts}));");

            if (compareReturn)
            {
                var col = method.ReturnColumn ?? "result";
                var retExpected = values[valueParamCount(method)];
                sb.AppendLine($"                            cells__.Add(CellCheck.For<{method.QualifiedReturnType}>(\"{escapeString(col)}\", actual__ret, \"{escapeString(retExpected)}\", {opts}));");
            }

            sb.AppendLine("                            return new WaitAttempt(cells__.TrueForAll(c => c.Status == ResultStatus.success), cells__.ToArray());");
        }
        else if (method.StepKind == "Check")
        {
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            sb.AppendLine($"                            var ok__ = {awaitKw}{target}.{method.MethodName}({args});");
            sb.AppendLine("                            var cell__ = new CellResult(\"result\", ok__ ? ResultStatus.success : ResultStatus.failed) { Expected = \"true\", Actual = ok__ ? \"true\" : \"false\" };");
            sb.AppendLine("                            return new WaitAttempt(ok__, new[] { cell__ });");
        }
        else
        {
            // void / no-throw action
            var args = buildSentenceArgs(method, values, step.DocString, scopeProvider, tableLiteral(step));
            sb.AppendLine($"                            {awaitKw}{target}.{method.MethodName}({args});");
            sb.AppendLine("                            return new WaitAttempt(true, System.Array.Empty<CellResult>());");
        }

        sb.AppendLine("                        }, ct, ctx);");
        sb.AppendLine("                    }));");
    }

    private static string emitCheckOptions(StepMethodInfo method)
    {
        if (method.ApproxTolerance.HasValue)
            return $"new CheckOptions {{ Tolerance = {method.ApproxTolerance.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)} }}";
        return "null";
    }

    private static string buildSentenceArgs(StepMethodInfo method, List<string> values, string? docString = null,
        string? scopeProvider = null, string? tableLiteral = null)
        => buildArgsFromCaptures(method.Parameters, values, docString, scopeProvider, tableLiteral);

    /// <summary>
    /// The C# expression building the step's trailing data table as a <c>Bobcat.StepTable</c>,
    /// or <c>null</c> when the step has none. Bound to a <c>StepTable</c> parameter.
    /// </summary>
    private static string? tableLiteral(StepInfo step)
    {
        if (step.TableHeaders == null || step.TableRows == null) return null;

        var headers = string.Join(", ", step.TableHeaders.Select(h => $"\"{escapeString(h)}\""));
        var rows = string.Join(", ", step.TableRows.Select(r =>
            "new string[] { " + string.Join(", ", r.Select(c => $"\"{escapeString(c)}\"")) + " }"));

        return $"new global::Bobcat.StepTable(new string[] {{ {headers} }}, new string[][] {{ {rows} }})";
    }

    /// <summary>
    /// Bind parameters to Cucumber captures positionally, skipping injected ones. A trailing
    /// DocString fills the first uncovered string parameter; a <c>StepTable</c> parameter takes
    /// <paramref name="tableLiteral"/> (or null when the step carries no table).
    /// </summary>
    private static string buildArgsFromCaptures(List<ParameterInfo> parameters, List<string> values,
        string? docString, string? scopeProvider, string? tableLiteral = null)
    {
        if (parameters.Count == 0) return "";

        var args = new List<string>();
        var vi = 0;
        foreach (var param in parameters)
        {
            if (param.Binding == ParameterBinding.Table)
            {
                args.Add(tableLiteral ?? "null");
            }
            else if (param.IsInjected)
            {
                args.Add(injectionExpression(param, scopeProvider));
            }
            else if (vi < values.Count)
            {
                args.Add(CucumberExpressionParser.ToCSharpLiteral(values[vi], param.Type));
                vi++;
            }
            else if (docString != null && param.Type == "string")
            {
                // A DocString fills the trailing string parameter not covered by captures.
                args.Add(CucumberExpressionParser.ToCSharpLiteral(docString, "string"));
                docString = null;
            }
            else
            {
                args.Add($"default({param.QualifiedType})");
            }
        }

        return string.Join(", ", args);
    }

    private static string buildTableRowArgs(StepMethodInfo method, List<string> headers, List<string> row,
        string? scopeProvider = null)
        => buildArgsFromColumns(method.Parameters, headers, row, scopeProvider);

    /// <summary>
    /// Bind parameters to a table row by header name, with injection for the rest.
    /// </summary>
    private static string buildArgsFromColumns(List<ParameterInfo> parameters, List<string> headers,
        List<string> row, string? scopeProvider)
    {
        var args = new List<string>();
        foreach (var param in parameters)
        {
            // A header match wins over convention-based injection; [FromScopedService] and
            // friends are the explicit override that wins over a header match.
            var colIndex = headers.FindIndex(h =>
                string.Equals(h, param.Name, StringComparison.OrdinalIgnoreCase));

            if (param.IsExplicitlyInjected || (param.IsInjected && colIndex < 0))
            {
                args.Add(injectionExpression(param, scopeProvider));
            }
            else if (colIndex >= 0 && colIndex < row.Count)
            {
                args.Add(CucumberExpressionParser.ToCSharpLiteral(row[colIndex], param.Type));
            }
            else
            {
                args.Add($"default({param.QualifiedType})");
            }
        }

        return string.Join(", ", args);
    }

    /// <summary>
    /// The C# expression that supplies an injected parameter. Scoped resolutions go through
    /// <paramref name="scopeProvider"/> when a <c>[NewScope]</c>/<c>[ScopePerRow]</c> child
    /// scope is open, otherwise through the scenario scope on the host resource.
    /// </summary>
    private static string injectionExpression(ParameterInfo p, string? scopeProvider)
    {
        var resource = p.ResourceName == null ? "null" : $"\"{escapeString(p.ResourceName)}\"";

        switch (p.Binding)
        {
            case ParameterBinding.StepContext:
                return "ctx";

            case ParameterBinding.Table:
                // Only sentence, Check, WaitFor and set-verification steps carry the table through
                // buildArgsFromCaptures; anywhere else (per-row [Table] calls, decision tables,
                // hooks) there is no whole table to hand over.
                return "null";

            case ParameterBinding.Resource:
                return $"ctx.GetResource<{p.QualifiedType}>({resource})";

            case ParameterBinding.RootService:
                return $"Bobcat.Runtime.HostResourceExtensions.GetRootService<{p.QualifiedType}>(ctx, {resource})";

            case ParameterBinding.KeyedService:
                var key = p.ServiceKey == null ? "null" : $"\"{escapeString(p.ServiceKey)}\"";
                return scopeProvider != null
                    ? $"Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<{p.QualifiedType}>({scopeProvider}, {key})"
                    : $"Bobcat.Runtime.HostResourceExtensions.GetKeyedHostService<{p.QualifiedType}>(ctx, {key}, {resource})";

            default:
                return scopeProvider != null
                    ? $"Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{p.QualifiedType}>({scopeProvider})"
                    : $"Bobcat.Runtime.HostResourceExtensions.GetHostService<{p.QualifiedType}>(ctx, {resource})";
        }
    }

    /// <summary>Number of parameters that consume a Cucumber capture.</summary>
    private static int valueParamCount(StepMethodInfo method)
    {
        var count = 0;
        foreach (var p in method.Parameters) if (!p.IsInjected) count++;
        return count;
    }

    /// <summary>The expression that opens a <c>[NewScope]</c>/<c>[ScopePerRow]</c> child scope.</summary>
    private static string childScopeExpression(StepMethodInfo method)
    {
        var resource = method.ScopeResourceName == null
            ? "null"
            : $"\"{escapeString(method.ScopeResourceName)}\"";
        return $"Bobcat.Runtime.HostResourceExtensions.CreateChildScope(ctx, {resource})";
    }

    /// <summary>The <c>using var</c> declaration that opens a child scope for a whole step.</summary>
    private static string childScopeStatement(StepMethodInfo method, string local)
        => $"using var {local} = {childScopeExpression(method)};";

    public static string SanitizeIdentifier(string text)
    {
        var sb = new StringBuilder();
        foreach (var c in text)
        {
            if (char.IsLetterOrDigit(c))
                sb.Append(c);
            else if (c == ' ')
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static string escapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
    }
}

public class MatchedScenario
{
    public ScenarioInfo Scenario { get; set; } = null!;
    public List<MatchedStep> Steps { get; set; } = new();
}

public class MatchedStep
{
    public StepInfo Step { get; set; } = null!;

    /// <summary>Set when the step matched a fixture/module step method.</summary>
    public StepMatcher.MatchResult? Match { get; set; }

    /// <summary>Set when the step matched a <c>[TableGrammar]</c> class instead.</summary>
    public StepMatcher.TableGrammarMatch? GrammarMatch { get; set; }
}
