<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bobcat.Alba\Bobcat.Alba.csproj" />
    <ProjectReference Include="..\Bobcat.Alba.SampleWeb\Bobcat.Alba.SampleWeb.csproj" />
    <ProjectReference Include="..\Bobcat.Alba.SampleJasperFxWeb\Bobcat.Alba.SampleJasperFxWeb.csproj" />
  </ItemGroup>

</Project>
